### ISSUE TITLE
Check depedencies via Gemnasium

### ISSUE THREAD

**Issue by levsthings** [hollowverse-archive/hollowverse#110]
So we got rid of Greenkeeper and we're manually updating our dependencies as we see fit.

To keep track of what's happening behind the scenes I suggest using [Gemnasium](https://gemnasium.com/). I've used this tool for a long time without an issue, all it does is just sends you some emails every now and then telling you about the new updates.

@msafih If you can hook us up with this tool and share the badge link with me, I'll update the `readme` to include the badge so that developers can go to our dependency page to see which packages have updated with corresponding `changelog` information.

**Comment by wholesomedev** [comment]
Great, I'll see if I can get to it this weekend!

**Comment by forabi** [comment]
@msafih Any progress on this?

**Comment by wholesomedev** [comment]
@forabi I'm afraid I haven't had a chance to look into this. Basically, Lev and I were trying to find a way to always keep our dependencies up to date and were considering different services for that. 

What do you think about this in general, do you have any opinion on which approach we should take? Should we go with Gemnasium or are there other solutions? We used Greenkeeper in the past but it was terrible. It didn't work correctly and it doesn't support Yarn.

**Comment by forabi** [comment]
I think with our decision to not have integration tests we should be careful about when to update our dependencies. Although theoretically minor and patch package updates should not break our code, package authors may unintentionally introduce breaking changes with minor updates. I don't feel comfortable automating this process. The main purpose of having a lock file is to avoid dependency updates that could cause our code to break.

**Comment by wholesomedev** [comment]
Alright, I'm okay with not doing this for now. We can revisit it in the future after we've laid down the Real Testing™ infrastructure.
