### ISSUE TITLE
Implement server-side rendering

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#13]

**Comment by deltaidea** [comment]
Notes for later:

- [Docs on `ReactDOMServer`](https://facebook.github.io/react/docs/react-dom-server.html)
- [Example of Express + server-side rendering](https://github.com/mhart/react-server-example)

**Comment by wholesomedev** [comment]
This is an issue that might arise again in the future. For now we don't wanna worry about it. Closing...
