### ISSUE TITLE
Idea to share common setup between repos

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#140]
Recently Rich Harris (of Rollup and Svelte's fame) announced a new project called [degit](https://github.com/Rich-Harris/degit/) which does scaffolding, like Yeoman. This reignited my interest in solving the problem of sharing common configs between repos. The limitation that degit and Yeoman have is that once a project is built from a template, it cannot be updated when the template gets updated. (I tried to solve this problem with [commonpkg](https://github.com/hollowverse/commonpkg), but that wasn't very successful. I don't think we're using commonpkg anymore? We should delete it.)

But degit gave me a new idea for solving this problem. We can utilize git. Here's how:

We create a new repo called `hollowverse/template`. This repo contains the initial template for our projects. Now, say we want to create a new project based on this template, say the new project is called `hollowbot`. To do that, we follow these steps:

1. Clone `hollowverse/template` to a folder called `hollowbot` with a command like
    
    ```
    git clone git@github.com:hollowverse/template.git hollowbot
    ```
1. Rename the `origin` remote to `template`
1. Create a new empty GitHub repo at `hollowverse/hollowbot` and copy its address to the clipboard
1. Add `hollowverse/hollowbot` as `origin` remote to the newly cloned repo
1. Checkout `master` from `template` remote and push it to `origin` and have it track `origin/master`
1. After completing these steps, you can say that you have successfully scaffolded the `hollowverse/hollowbot` repo based on the `hollowverse/template` repo. And you can continue to build the `hollowverse/hollowbot` and push to `origin/master` which is `hollowverse/hollowbot#master`

Then in the future, when we update `hollowverse/template` with new configurations, you can merge `hollowverse/template` to `hollowverse/hollowbot`.

The mental model of this approach is similar to how, in git flow, a developer keeps merging master back into their feature branch to get the latest updates. In this approach you can think of the template repo as master and the repo which was built from the template as the feature branch. You periodically merge the template back into your "feature" repo. The difference is that master and the feature branches live in separate repos but they share common ancestor commits.

If this approach makes sense, we can try to follow it in the [`hollowbot`](https://github.com/hollowverse/hollowbot/) repo and if it proves successful, I can spend some time to see if I can abstract some of the steps above into a CLI. It could be a fun little pet project.

(One challenge that I'm not clear on how to solve is how to retrofit this approach onto a repo that wasn't started with it. Like, how can we base `hollowverse/hollowverse` on `hollowverse/template` even though `hollowverse/hollowverse` doesn't have common ancestor commits with `hollowverse/template`? That's some thing I can look into though if we decide to try this approach.)

**Comment by forabi** [comment]
@msafih I always had this idea. But is it actually feasible? Although our repos might share some common configuration files, there could be differences in the location of those files, or probably in the contents of the files. Let's take hollowbot as an example. Since it is a Node.js app, it has to be compiled with CommonJS modules. On the other hand, Webpack takes advantage of ES Modules to remove unused imports, this is important for our client-side app. If we were to base these two repos on `hollowverse/template`, how should these differences be handled? Would we have to resolve the conflicts every time we update the template? If so, does that have any advantages over manually managing and updating these files?

> (One challenge that I'm not clear on how to solve is how to retrofit this approach onto a repo that wasn't started with it. Like, how can we base hollowverse/hollowverse on hollowverse/template even though hollowverse/hollowverse doesn't have common ancestor commits with hollowverse/template? That's some thing I can look into though if we decide to try this approach.)

I can't think of a way to solve this. As far as I understand, there has to be at least on common ancestor in the git trees of the two repos. We can test with local clones and see if and how git handles merging two different trees from two remotes.

Another idea that might be worth a shot is placing all our projects in one monolithic repo (with a tool like [lerna](https://github.com/lerna/lerna)). Facebook and Goolge have large monolithic repos. But this may also introduce a lot of complexity when dealing with building and deployment. It does not look like there are many open source tools to handle these workflows.

**Comment by msafih** [comment]
So I guess there's no easy solution for this. In that case, it seems to me that we should just utilize extensible configuration files where possible. 

For example `.eslintrc.json`, `tsconfig.json`, and `tslint.json` can all be extended. We should put these files and any other files that can be extended in our [common-config](https://github.com/hollowverse/common-config) repo and extend them from our various repos.

To include `common-config` in different repos, we don't have to publish it to npm. We can continue to include it as a GitHub URL as we do today.

What do you think @forabi, should we limit our template reusability ambitions to doing just that for now?

**Comment by wholesomedev** [comment]
So I guess there's no easy solution for this. In that case, it seems to me that we should just utilize extensible configuration files where possible. 

For example `.eslintrc.json`, `tsconfig.json`, and `tslint.json` can all be extended. We should put these files and any other files that can be extended in our [common-config](https://github.com/hollowverse/common-config) repo and extend them from our various repos.

To include `common-config` in different repos, we don't have to publish it to npm. We can continue to include it as a GitHub URL as we do today.

What do you think, should we limit our template reusability ambitions to doing just that for now?

**Comment by forabi** [comment]
> For example .eslintrc.json, tsconfig.json, and tslint.json can all be extended. We should put these files and any other files that can be extended in our common-config repo and extend them from our various repos.

I will submit PRs to move these files to the [common-config repo](https://github.com/hollowverse/common-config).

> To include common-config in different repos, we don't have to publish it to npm. We can continue to include it as a GitHub URL as we do today.

`common-config` is actually already [published](https://www.npmjs.com/package/@hollowverse/common-config) to npm.

> What do you think, should we limit our template reusability ambitions to doing just that for now?

I would really like to tackle this but there just does not seem to be a good solution. It seems to me that all the attempted solutions expect that the projects are initialized with the shared configuration once and each project continues from there to modify the configuration files separately.

**Comment by wholesomedev** [comment]
> `common-config` is actually already [published](https://www.npmjs.com/package/@hollowverse/common-config) to npm.

Yeah but I don't think we should use the published version. We should instead link to GitHub directly. That way we don't have to worry about publishing it. No?

**Comment by forabi** [comment]
> Yeah but I don't think we should use the published version. We should instead link to GitHub directly. That way we don't have to worry about publishing it. No?

We can do that, or we can set up CI to automatically publish new versions to npm. What do you think?

**Comment by wholesomedev** [comment]
> We can do that, or we can set up CI to automatically publish new versions to npm. What do you think?

I think if we can get away with not publishing, we should do that because that would be a simpler setup.

**Comment by forabi** [comment]
> I think if we can get away with not publishing, we should do that because that would be a simpler setup.

I think we can get away with it since we do not need versioning, at least for now. It's hard to break the common-config repo in a way that introduces incompatibilities.

**Comment by wholesomedev** [comment]
Cool. I'll close this issue then.

By the way, I've moved `commonpkg` to `hollowverse-archive/commonpkg`
