### ISSUE TITLE
Define and decide on the supported breakpoints

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#15]
We need to decide on how many breakpoints we're gonna support and what those breakpoints are.

I think we should have two breakpoints: 

1. Phablet and smaller
1. Bigger than phablet

As for what those breakpoints should be, I'm not sure yet. We probably need to research that.

**Comment by deltaidea** [comment]
Bootstrap uses [the following breakpoints](https://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints):

```Sass
// Extra small devices (portrait phones, less than 576px)
// No media query since this is the default in Bootstrap

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

Hollowverse may not use Bootstrap, but they still must know their stuff, right?

We can start with 768 and 992 as breakpoints. I'm not sure how they chose exactly these numbers but they seem realistic.

Do you want me to check other frameworks and real websites first?

**Comment by wholesomedev** [comment]
I think it's a good idea to go by what Bootstrap has defined as breakpoints. So I guess we can support two breakpoints:

1. 768px and bigger
1. Smaller than 768px

We would need to document that someone once we decide on it.

Thoughts?

**Comment by deltaidea** [comment]
That's one breakpoint (768px) to be exact but I get your point.

I came across a surprisingly simple and good advice on SO: http://stackoverflow.com/a/16444844

> Rather than try to target `@media` rules at specific devices, it is arguably more practical to base them on your particular layout instead. That is, gradually narrow your desktop browser window and observe the natural breakpoints for your content. It's different for every site. As long as the design flows well at each browser width, it should work pretty reliably on any screen size (and there are lots and lots of them out there.)

And in the comments:

> if you try to chase screen sizes you'll get overwhelmed, as there are many of them. Let your layout dictate where the breakpoints need to be. You may only need one or two. :)

Let's defer this issue until we have at least one or two pages working on small screens (like 500px wide), and then see what needs to be adjusted and at what point.

> Start with the small screen first, then expand until it looks like shit. TIME FOR A BREAKPOINT!
>
> — http://bradfrost.com/blog/post/7-habits-of-highly-effective-media-queries/

I think it just clicked in my mind what "mobile-first" means.

**Comment by wholesomedev** [comment]
So you're saying let's just design for mobile for now, and wait for "shit. TIME FOR A BREAKPOINT!"? Sounds good to me. 

Should we add this bit to UX guidelines?

**Comment by deltaidea** [comment]
I imagine this is a one time thing, not really a guideline. Let's design profile creation and display pages, that should be enough to choose breakpoints.

**Comment by wholesomedev** [comment]
👍

**Comment by wholesomedev** [comment]
We've decided to only design for mobile for now. 0 breakpoints.
