### ISSUE TITLE
Add code quality controls to other repos

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#152]
I think we need to add linting, prettier, etc to other repos such as [hollowverse-docker](https://github.com/hollowverse/hollowverse-docker) and [common-config](https://github.com/hollowverse/common-config) now that they contain actual code.

Let's also hookup `validateFileNames.js` when we do it.

* [x] ~[hollowverse/hollowverse-docker](/hollowverse/hollowverse-docker)~ (no longer needed once https://github.com/hollowverse/hollowverse-docker/pull/15 is merged, as there won't be any code)
* [x] [hollowverse/lets-encrypt](/hollowverse/lets-encrypt)
* [x] [hollowverse/hollowbot](/hollowverse/hollowbot) (we still need to move to App Engine, hook up CI/CD)
* [x] [hollowverse/hollowverse](/hollowverse/hollowverse) (tracked in #162, already has them, but we need to move to using shared configuration from [hollowverse/common](/hollowverse/common) as well)
* [x] [hollowverse/common](/hollowverse/common) (tracked in https://github.com/hollowverse/common/pull/8)

**Comment by forabi** [comment]
I added a checklist to the issue and checked off the repos that now have code quality controls.
