### ISSUE TITLE
Fix outages of load testing and deployments

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#154]
We are noticing outages that occur when we deploy through the CI and when we perform load testing. We need to fix those.

**Comment by forabi** [comment]
According to GCP support, outages during deployment should be fixed by #159.

**Comment by wholesomedev** [comment]
@forabi Let's wait to verify that before closing.

**Comment by forabi** [comment]
@msafih There is still the load testing outages, so this should not be closed for now anyway.

**Comment by wholesomedev** [comment]
We performed some testing and deployments on AWS and there were no outages.
