### ISSUE TITLE
Update build status badge on README

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#178]

**Comment by forabi** [comment]
@msafih I actually looked for some simple status badge snippet we could copy and paste in our README, but it looks like CodeBuild does not provide one. It's integrated with a pretty complex notification system (AWS SNS) but it does have this simple snippet 😅 . Anyway, I will need to do some research to make the final decision between CodeBuild and Travis.

**Comment by forabi** [comment]
No longer relevant, because we decided to use Travis.
