### ISSUE TITLE
Security of Hollowbot

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#182]
As far as I understand, anyone can authorize Hollowbot to join their Discord server just by knowing the client ID of the bot. Although the ID does not show anywhere in Discord's UI, it's not supposed to be a secret. I think it can be obtained using the Discord API.

This poses a huge security risk, because if anyone could add Hollowbot to their room, they can instruct it to deploy PRs (#167) or do whatever tasks it is authorized to do.

One way to mitigate this is to wrap any sensitive response handler in a `requireAuthorization` function that checks the user and room ID from which the request was initiated. Hubot provides this information.

We can use this information to restrict sensitive operations to authorized contributors. This list can be hardcoded as a JSON file for example, or fetched dynamically using the Discord API.

One problem with this approach is that we will need to _remember_ and _be aware_ of this security risk every time we add a new response handler. So it's not a one-time mitigation.

**Comment by wholesomedev** [comment]
Can we make HollowBot only work if it is on the Discord Hollowverse server and base access rights on the member roles? For example, you have a "committer" role on the Discord Hollowverse server—can we make HollowBot check your role to decide whether you are allowed to perform the action or not?

By the way, why are we building HollowBot now, does AWS not have convenient traffic splitting, etc? I remember when we were on GAE we said maybe we'll try to postpone HollowBot development until a bit later even if it means we do things manually for now?

**Comment by forabi** [comment]
@msafih We are building it for #167. As discussed in that issue, it is not possible to build and deploy PRs with just Travis because PRs do not have access to the secrets. We need Hollowbot for that. However, we can achieve a similar result by manually merging PRs to temporary branches in this repository, and letting Travis do the deployment. It's your call.

We cannot restrict what servers Hollowbot can join, but we definitely can check the IDs of the user and server of each received message, and with some effort I assume we can query Discord's API for the roles assigned to each user ID.

**Comment by forabi** [comment]
@msafih AWS does not have a built-in traffic splitting feature. We will need to implement our own solution for this (similar to Release Manager).

**Comment by wholesomedev** [comment]
As we discussed on Discord, we'll put off hollowbot development to a later date. But this was a good discussion. Now we have ideas on how to proceed when we resume working on hollowbot.
