### ISSUE TITLE
Update workflow wiki for forking and sending PRs

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#188]
We need to update the workflow wiki to mention that everyone has to fork and send a PR

**Comment by forabi** [comment]
Please see my comment here: https://github.com/hollowverse/hollowverse/pull/184#issuecomment-331106316

What do you think?

**Comment by wholesomedev** [comment]
Yeah, I think that works. I can close this for now until we find out more about which workflow is best.
