### ISSUE TITLE
Build "Add Notable Person" Page

### ISSUE THREAD

**Issue by deltaidea** [hollowverse-archive/hollowverse#2]
This task depends on [Build "Create Profile" Page](https://github.com/hollowverse/hollowverse/milestone/2) milestone

---

We'll need the following data set about each person:

- Name (string)
- Short name (string) - for user-friendly URLs like on the old site
- Religion (text)
- Political views (text)
- Article (text)
- Last update (datetime)

Example of a celebrity page on the old website: http://hollowverse.com/bill-gates/

**Comment by wholesomedev** [comment]
So here's what I imagine for the new Hollowverse (not necessarily the design and layout, but the content):

![img_4120](https://cloud.githubusercontent.com/assets/26730388/24535877/b471d3fe-158b-11e7-8e3f-ec438d1c983d.JPG)

As you can see, we have the name of the celebrity. Picture. Summary. Labels. And then a list of Events.

Ideally, all of these should be user-generated. The way each piece of content is moderated and promoted is by voting. For example, anyone should be able to add a summary. Users will vote on the different summaries. The highest ranking summary will get displayed.

We need to think about the ranking criteria. One idea I've contemplated is a combination of votes and time to determine the rank. Content loses weight the older it gets. This way we give new content chance to surface, and the content of the website in general stays fresh.

Anyway, there are a lot of challenges in the model I'm proposing. I'm sure you'll see those challenges for yourself if you spend a few minutes thinking about this model, but we need to think of an approach to simplify things and build a minimum viable product that we can then continue to reshape and improve.

**Comment by forabi** [comment]
@msafih What do you think is still needed to close this?

**Comment by wholesomedev** [comment]
@forabi If we look at the [milestone that this issue represents](https://github.com/hollowverse/hollowverse/milestone/2), we see that there are two issues open: #21 and #20. I think #21 can be removed from this milestone because v1 is going to be a static website. And we've decided on #20 on Discord, so I'll add a summary of our decision to the issue and close it...which I guess means this issue too can be closed...

**Comment by wholesomedev** [comment]
Oh, well, I just realized that this issue is for **adding** a NP, not for **displaying** an NP. Anyway, we have a long way before we can think about this one, so let's just keep it closed.
