### ISSUE TITLE
Investigate feasability of implementing server-side rendering

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#203]
## Why we should implement server-side rendering

* While it's true that SSR is not a panacea and the complexity of implementing it may not be worth it for interactive web apps, Hollowverse is a content-first web app with a few interactions, so it should not depend on JS to show its content. Ideally users should be able to browse the web app even with JavaScript disabled.
* Having the markup delivered and parsed before JS is even fetched will enhance our first meaningful paint considerably
* Having the markup delivered as HTML allows the browser to start parsing and rendering components before the page is finished loading. That's not the case for JS-rendered components.
* We can also push server-rendered markup as it's being produced using streams, this should further enhance our time to first paint.
* SSR should also be beneficial from an SEO perspective.

## Is it possible?

There is no "ultimate" solution to implementing SSR, and it is quite complex to write code that will work in browsers and Node.js, especially when using Webpack-specific syntax for things like file loaders.

I think this is the best time to start looking into this issue because the codebase is still small and there are not much browser-specific code.

## Where we are now

For reference, this is [WebPageTest results](https://www.webpagetest.org/result/171110_25_abcf154044c5010ebcb5986662d65599/) for https://hollowverse.com/tom-hanks?branch=new-app at the time or writing this issue:

![screenshot_20171110_144808](https://user-images.githubusercontent.com/1012761/32660874-4c52d446-c62d-11e7-8da7-2f6264fea16b.png)

(Note that some of the problems in this report do not have anything to do with SSR)

![screenshot_20171110_153942](https://user-images.githubusercontent.com/1012761/32660893-64be1e32-c62d-11e7-8daf-cf3f442d1870.png)

## Relevant Links
* https://github.com/faceyspacey/babel-plugin-dual-import
* https://github.com/faceyspacey/extract-css-chunks-webpack-plugin

**Comment by wholesomedev** [comment]
I really agree with this point:

> While it's true that SSR is not a panacea and the complexity of implementing it may not be worth it for interactive web apps, Hollowverse is a content-first web app with a few interactions, so it should not depend on JS to show its content.

What about rendering the page inside a headless browser server side and sending that down the pipe?

**Comment by forabi** [comment]
> What about rendering the page inside a headless browser server side and sending that down the pipe?

I thought about this. My concern with this approach is that it may not be efficient. Will we need to render the page for every request? That would be extremely inefficient as Webpack builds take at least 0.5-1m. Not to mention the load on CPU.

I'll look more into that.

**Comment by wholesomedev** [comment]
Yeah. I see your point. The other thing is, what if we use headless Chrome and then serve the page to a Safari user? Or use headless webkit and serve the page to a Chrome user, will things still work?

**Comment by forabi** [comment]
> Yeah. I see your point. The other thing is, what if we use headless Chrome and then serve the page to a Safari user? Or use headless webkit and serve the page to a Chrome user, will things still work?

That would work. We just need the HTML markup to send to the client. However, if the markup is just a little bit different (due to code handling browser-specific bugs, for example), React/Preact may throw the entire page and re-render it again when JS is parsed. 

Anyway, the markup will still be delivered sooner and users can read something before JS kicks in.
