### ISSUE TITLE
Investigate how to improve caching and compression for static files

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#204]
[WebPageTest results](https://www.webpagetest.org/result/171110_25_abcf154044c5010ebcb5986662d65599/1/performance_optimization/) show that we are not doing a great job at caching and compressing our Webpack bundles. There is a lot of room for improvement. Although the JS and CSS files are minified, they are not gzipped. They do not have any cache control headers either.

Some possible solutions we could look into:
* Use a CDN, probably Cloudfront, in front of the whole web app, but only cache static assets. This should be done carefully to avoid any possible security problems caused by caching pages with cookies. We should also take into account how this could affect Release Manager routing.
* Use Amazon S3 to store the build artifacts, and Cloudfront in front of the S3 bucket, and point the client to fetch the static files from S3.
* Do all the work on our app server:
  * Customize caching headers on our app server to set `max-age` or `expires` to a reasonably long time. We could also try [`Cache-Control: immutable`](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/). This tells the browser to store the resource permanently and never ask for it again (not even check if it has expired). This should be safe for our static files as they all contain unique content-based hashes in their names.
  * Use a Node.js module to enable gzip and brotli compression for static files..

**Comment by wholesomedev** [comment]
> Use a CDN, probably Cloudfront, in front of the whole web app, but only cache static assets. This should be done carefully to avoid any possible security problems caused by caching pages with cookies. We should also take into account how this could affect Release Manager routing.

I'm just a little concerned about this. If it turns out to complicate things, perhaps it's worth putting off until later?

**Comment by forabi** [comment]
> I'm just a little concerned about this. If it turns out to complicate things, perhaps it's worth putting off until later?

I agree. This is the least safe approach. What's your opinion on the other solutions?

**Comment by wholesomedev** [comment]
@forabi I like the other solutions because they seem both easy to apply and might have big impact.

**Comment by forabi** [comment]
@msafih I've been reading CloudFront docs and it looks like we can specify a path to cache when creating a CloudFront distribution. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginPath

With #210, static assets are now in a separate path (`/static`) so we should be able to use CloudFront for static files.
