### ISSUE TITLE
Improve securityheaders.io rating for our web app and API

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#205]
Here is [securityheaders.io rating](https://securityheaders.io/?q=https%3A%2F%2Fhollowverse.com%2FTom_Hanks%3Fbranch%3Dnew-app&followRedirects=on) for https://hollowverse.com/Tom_Hanks?branch=new-app at the time of writing this issue:

![screenshot_20171110_161356](https://user-images.githubusercontent.com/1012761/32662280-9f49c83a-c632-11e7-968e-10f3d3e8cb73.png)

And here is [the rating for our API](https://securityheaders.io/?q=https%3A%2F%2Fapi.hollowverse.com%2Fgraphql&followRedirects=on):
![screenshot_20171110_161421](https://user-images.githubusercontent.com/1012761/32662166-3add47d2-c632-11e7-9ac1-ea94de9c39d3.png)

Most of these headers are trivial to implement, with the exception of `Content-Security-Policy` which would need careful testing as it enforces a lot of restrictions on what domains can be used to load scripts and styles, and whether we can use `eval()` in JS (this may break some JS libraries). We could start by telling the browser to only report violations of the policy using a service like https://report-uri.com/ but not enforce it. We can then monitor the violations and make changes accordingly.

## Relevant Links
* https://github.com/helmetjs/helmet

**Comment by forabi** [comment]
#208 enhanced our rating on securityheaders.io to B.

https://securityheaders.io/?q=https%3A%2F%2Fhollowverse.com&followRedirects=on

We can still improve by increasing HTST `max-age` to at least 30 days and implementing `Content-Security-Policy`.

We should also configure these headers for the API.

**Comment by forabi** [comment]
With #209 and hollowverse/api#15 merged, we now get an A for both the app server and the API. `Content-Security-Policy` is relevant for the API and we can look into implementing it for the app server in another issue.

![screenshot_20171112_045819](https://user-images.githubusercontent.com/1012761/32695471-1f709ffa-c766-11e7-86b9-b14b7306fa63.png)

![screenshot_20171112_045840](https://user-images.githubusercontent.com/1012761/32695473-28a6a646-c766-11e7-9cab-fc5afb19be16.png)

**Comment by wholesomedev** [comment]
Awesome! 👍
