### ISSUE TITLE
Should we remove user comments entirely?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#207]
I'm thinking implementing user comments on our website poses technical and design challenges incommensurate with their benefits. If we remove user comments, users can still post comments through Facebook comments. 

The immediate problem I see with removing user comments is that we will lose a lot of content when we do the migration. But other than that, I think it's a good long-term decision.

Thoughts?

Related: https://github.com/hollowverse/design/pull/15

**Comment by forabi** [comment]
I think having two types of comments might be confusing from a UX perspective. I'm OK with removing event comments. But that can be solved by moving the comments on events to individual event pages.

One issue with removing event comments is that we will be depending on Facebook for even a larger part of our content. Event comments are stored in our database and can, theoretically, be posted without using Facebook.

**Comment by wholesomedev** [comment]
@forabi Yes, we'll be depending on Facebook for a larger part of our content, but I feel like user comments is not a critical part of our content, and it's difficult for us to implement in-house. If it's any consolation, Facebook comments can be exported, so theoretically, we can store them later on in an alternative way.

Anyway, thanks for the feedback. For now, let's do away with event comments!
