### ISSUE TITLE
Check-in a Prettier config file for editor extensions

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#211]
Can we check-in a Prettier config file which will inform Prettier extensions in editors of how to format code?

If so, can we put it in our `common` repo and extend it from the other repos?

**Comment by forabi** [comment]
The unofficial prettier extension for VS Code can read configuration from a field named `prettier` in `package.json`. However, this field is not something officially supported by prettier and I don't know of any other code editor extensions that support it. So we need to duplicate the configuration for VS Code extension and the CLI command which is run on every commit.

**Comment by forabi** [comment]
Relevant issue: https://github.com/prettier/prettier/issues/62

**Comment by wholesomedev** [comment]
I'm okay with either approach.

**Comment by forabi** [comment]
> I'm okay with either approach.

So should we add the "prettier" field for VS Code extension? I don't see the point. The files will be prettified when committed anyway.

**Comment by wholesomedev** [comment]
Problem is someone (like me) might have different default configurations in their editor. Now whenever they edit one of our files, the whole file gets reformatted and it's a little jarring. That's what I'm hoping to solve.

**Comment by wholesomedev** [comment]
@forabi Can't we get the CLI and editor extensions both to read from one of these config files?
https://prettier.io/docs/en/configuration.html

**Comment by forabi** [comment]
> Can't we get the CLI to read from one of these config files?

Sorry, I didn't realize that prettier supports a configuration file. I will look into that.
