### ISSUE TITLE
Enable `master` branch protection on admins

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#214]
I think we should enable `master` branch protection even for admins to prevent accidental pushes to `master`. This is good practice because with our current setup any update to `master` triggers a build and a deployment.

If occasionally we need to push directly to `master` for whatever reason, we can turn off this protection temporarily and re-enable it after we're done.

I've gone ahead and enabled the protection. Feel free to close this issue if this is all good.

**Comment by forabi** [comment]
I thought that was already enabled. I'm on mobile now, will check later.

**Comment by forabi** [comment]
I just checked, `master` protection is enforced for admins as well.
