### ISSUE TITLE
Look into separating Hollowverse AWS resources from resources for other websites

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#222]
Currently, under the same AWS account we have Hollowverse.com as well as a few other unrelated websites, such as DubaiEmploymentTips.com

Is it possible to move the other websites to a separate AWS account? I think that'll make things cleaner for the long term.

It's something to look into when time allows.

**Comment by forabi** [comment]
I've been looking into how to do this. According to AWS documentation, this can be done by creating a "machine image" based on the current EC2 instance hosting the other websites and sharing it with the new AWS account. Once shared, the new AWS account can boot a new EC2 instance from the shared image. This of course does not move IPs, domains or other network settings so additional work might be required to get the websites running on the new AWS account.

**Comment by forabi** [comment]
Can you create a new AWS account and give me access?

**Comment by forabi** [comment]
The move to the new account is now complete. Closing.
