### ISSUE TITLE
Decide on how to use and implement CloudFront CDN correctly

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#232]
As we discussed earlier, putting Release Manager in front of the CDN takes away one of the main benefits of the CDN which is the CDN's ability to route the request to the closest server geographically.

However, I'm wondering if it would still make sense to use the CloudFront CDN as a caching layer so that Release Manager will not be continuously hitting our web servers all the time. Instead, it'll get the cached page from CloudFront.

**Comment by forabi** [comment]
With CloudFront enabled and [`lambda-assign-env`](https://github.com/hollowverse/lambda-assign-env) implemented, we can close this! :tada:
