### ISSUE TITLE
Link directly to the configurations of our AWS services

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#233]
I think it would be beneficial to create a wiki page to document the wiki services we use. We could also document how each one of those services is configured.

Is exposing our AWS configurations publicly opens us to security risks? If not, can we create a readonly IAM that allows anyone to log into our services and view how they are configured?

**Comment by forabi** [comment]
> Is exposing our AWS configurations publicly opens us to security risks?

Definitely. Even reading some stuff is a security issue. For example, people having access to the deployed versions on Elastic Beanstalk can download any version of the app ever deployed, extract it, and read the decrypted secrets.

**Comment by wholesomedev** [comment]
@forabi can we make it so that only configurations are viewable while
blocking access to sensitive data? The reason I think this is beneficial is
because it will serve as always-up-to-date documentation. It would be
better than us having to manually keep documentation up to date.

**Comment by forabi** [comment]
What sort of configurations are you referring to exactly?

**Comment by wholesomedev** [comment]
I would imagine if we were to write documentation of how we use AWS
services, we would also need to mention how we have those services
configured. It would be cool if were able to tell developers to log into
our AWS account and view how services are configured instead.

If we can expose all of our non-sensitive configurations, that would be
good.

**Comment by forabi** [comment]
@wholesomedev I've created [a new Wiki page](https://github.com/hollowverse/hollowverse/wiki/AWS-Services) for the services we currently use.

With regard to exposing our configurations for public, I still think it's dangerous. The reason I think it's dangerous is because we are starting by exposing everything, and then trying to hide some sensitive data. It's always easy to miss something.

However, I think if we are going with this, the first thing that we should do is remove all the secrets from our repos and instead use the recently announced [AWS Secrets Manager](https://aws.amazon.com/blogs/aws/aws-secrets-manager-store-distribute-and-rotate-credentials-securely/) or the older [Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html). These provide a secure way to access secrets and limit access to specific IAM roles/users. The secrets are accessed at runtime so there won't be any sensitive data in the build artifacts or in AWS Lambda dashboard.

**Comment by wholesomedev** [comment]
@forabi Thanks for creating that wiki.

I'm okay with going the other way, that is create an IAM that has access to nothing, and we only whitelist the things that we want to publicly document. I'm also okay with using AWS Secrets Manager or the older system.

I do think that being able to link to specific AWS configurations from our documentation will provide a lot of value. We may not even need the AWS Services wiki then.

**Comment by wholesomedev** [comment]
This issue is currently pending completion of #451 

Once #451 is closed, we'll be able to link directly to the AWS services we use and their configurations in https://github.com/hollowverse/architecture

**Comment by wholesomedev** [comment]
@forabi do you think it would be possible now to link to our AWS configurations?

Can we make some AWS configurations public or will the viewer always have to log-in?

If the viewer has to log-in, can we make our policy so that any AWS account can see our configurations?

**Comment by forabi** [comment]
> @forabi do you think it would be possible now to link to our AWS configurations?

Yeah, I think we can start working on this.

> Can we make some AWS configurations public or will the viewer always have to log-in?

Not sure, I'll look into that.

> If the viewer has to log-in, can we make our policy so that any AWS account can see our configurations?

Not sure either :sweat:

**Comment by wholesomedev** [comment]
I wonder if something like the [AWS Config](https://aws.amazon.com/config/) service can help with what we're trying to achieve here?

Like if we can expose our configurations through API calls, then we could make a web page that queries and displays the configurations? Just a thought...

**Comment by forabi** [comment]
> I wonder if something like the AWS Config service can help with what we're trying to achieve here?

I took a preliminary look at AWS Config a couple weeks ago. I'm still not very familiar with it and what it can do exactly, but it looks like we need to set it up anyway for #478 (this seems to be the most straightforward way https://splunkbase.splunk.com/app/1274/).

**Comment by wholesomedev** [comment]
@forabi I'm assuming AWS Config is like a reporting service for our AWS resource configurations? 🤷

If my assumption is right, then I think it would be good to pipe AWS Config data to Splunk.

I just found out that using Splunk, we can create embeddable reports which can be iframed in any webpage and viewed by anyone. That, with AWS Config data, might just give us what we're trying to achieve in this issue (#233).

> it looks like we need to set [AWS Config] up anyway for #478

I don't understand, though, why you're saying AWS Config is required for #478? Why would AWS Config, which presumably reports on configurations, be needed to parse unrelated AWS logs in Splunk?

**Comment by forabi** [comment]
> Why would AWS Config, which presumably reports on configurations, be needed to parse unrelated AWS logs in Splunk?

The AWS add-on for Splunk can parse and analyze CloudWatch logs (which is what we need). The [very first step to configure this add-on](
https://docs.splunk.com/Documentation/AddOns/released/AWS/ConfigureAWS) is to set up AWS Config. I assume this add-on needs to access service configuration in order to find the required log groups in CloudWatch. Not completely sure though.

**Comment by forabi** [comment]
Or maybe I'm just misinterpreting the docs and each service (AWS Config, CloudWatch, ...etc.) can be configured individually without having to set up the other services.

**Comment by wholesomedev** [comment]
Another thing I wondered about for this issue is if it were possible to configure AWS using text files (yml or json) that can be uploaded to AWS. That way we would host our configurations on GitHub and deploy them to AWS when modified.

**Comment by forabi** [comment]
> Another thing I wondered about for this issue is if it were possible to configure AWS using text files (yml or json) that can be uploaded to AWS.

Isn't that kind of the same thing as `serverless.yml`? Sometimes Serverless fields map directly to the corresponding CloudFormation fields.

**Comment by wholesomedev** [comment]
>Isn't that kind of the same thing as `serverless.yml`? Sometimes Serverless fields map directly to the corresponding CloudFormation fields.

Yes, it is, but I meant it in a more strict manner where all of our AWS configurations have to come from version-controlled text files. It is just an idea. There's probably no such thing :)

**Comment by wholesomedev** [comment]
Hooking up AWS Config to Splunk seems to be our best bet for now

**Comment by forabi** [comment]
> I meant it in a more strict manner where all of our AWS configurations have to come from version-controlled text files

Yeah, that would be truly awesome. We would be able to update and even re-deploy the entire Hollowverse architecture from scratch using these config files. That's why I've been trying to move more and more settings from manual configuration in AWS console to `serverless.yml` plugins.

> Hooking up AWS Config to Splunk seems to be our best bet for now

That's what I'm going to look into next.

**Comment by wholesomedev** [comment]
@forabi Looking at the [CloudFormation page](https://aws.amazon.com/cloudformation/), it says:

> CloudFormation allows you to use a simple text file to model and provision, in an automated and secure manner, all the resources needed for your applications across all regions and accounts.

🤔

**Comment by forabi** [comment]
What's strange about that? Serverless uses CloudFormation behind the scenes :smile: 

All our services are CloudFormation stacks (with the exception of Route 53 records and the relational databases which are currently managed manually):

![screenshot from 2018-05-20 22-32-15](https://user-images.githubusercontent.com/1012761/40282837-ab448ba2-5c7d-11e8-924a-9abc52fe3c85.png)

I think we can move the Route 53 and database resources to Serverless so they become fully managed by CloudFormation.

**Comment by wholesomedev** [comment]
If we manage to move out of AWS UI and into deployable config files, we wouldn't have a need to link to AWS config UI directly from our docs. We would be able to link to our config files in the docs. I've created another issue (#495) for us to look into moving out of AWS UI and into deployable config files.

**Comment by forabi** [comment]
I think we can work on this now. Want me to handle it?

**Comment by wholesomedev** [comment]
> I think we can work on this now. Want me to handle it?

Sure! I think that might be better since you have more knowledge about those configurations?

**Comment by forabi** [comment]
Okay! I'll do it.

**Comment by forabi** [comment]
I'm having struggle determining where we are going to link to the new infrastructure config files :sweat_smile:. I mean, the architecture documents do not have references to anything that's currently managed by the infrastructure repo. Should I update [the Services page](https://github.com/hollowverse/hollowverse/wiki/AWS-Services) to mention each single service that is used and how it is used? I feel like this work is redundant considering that the code in `hollowverse/infrastructure` already has extensive comments and is always going to be up-to-date and the source of truth for the infrastructure.

**Comment by wholesomedev** [comment]
@forabi 

[Serving index.html](https://github.com/hollowverse/architecture/blob/master/architectures/serveIndexHtml.md) references: 

* Route 53
* hollowverse.com CloudFront distribution

[After Downloading index.html](https://github.com/hollowverse/architecture/blob/master/architectures/afterDownloadingIndexHtml.md) references:

* API
* photos.hollowverse.com
* Aurora
* S3 bucket of photos.hollowverse.com
* Logging

[hollowverse.com CloudFront distribution](https://github.com/hollowverse/architecture/blob/master/architectures/hollowverseComCloudFront.md) and [Origin Server](https://github.com/hollowverse/architecture/blob/master/architectures/originServer.md) reference:

* Several Lambda functions

I think for things that are managed by Serverless, we should link to their Serverless configurations. Some of the things above are managed by Terraform. We can link to their Terraform configurations?

What do you think?

**Comment by wholesomedev** [comment]
Perhaps we should close https://github.com/hollowverse/hollowverse/issues/495 first?

**Comment by wholesomedev** [comment]
> Should I update the Services page to mention each single service that is used and how it is used? I feel like this work is redundant

I agree. I think with `hollowverse/infrastructure`, we can delete the Services wiki page

**Comment by forabi** [comment]
I've removed the services page and added a link to the new Infrastructure Overview page. I'm going to merge hollowverse/hollowverse#96 (although I wanted to finish work on Atlantis first, but that's okay too).
