### ISSUE TITLE
Search icon doesn't show upon a hard reload on an NP page

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#235]

**Comment by forabi** [comment]
I've only been able to reproduce this in development. I tracked this down to an issue in `svg-sprite-loader` where the generated icon URL is malformed:

```html
<svg>
  <use href="/static//home/f/Projects/hollowverse/hollowverse/src/app/icons/search.svg" />
</svg>
```

This is clearly a bug, but I've only seen it once. It could have been fixed as a side effect of refactoring or upgrading dependencies in #230. Have you been able to reproduce this in production?

**Comment by forabi** [comment]
I was able to reproduce this issue again, it seems to show up randomly. However, I replaced all instances of `path.resolve` with `path.join` in Webpack config, and it looks like that did the trick. I'm no longer able to reproduce this. The fix will land with #230.

**Comment by forabi** [comment]
Nope, it wasn't fixed. It was just a coincidence that I wasn't able to reproduce it after replacing `path.resolve`. This is driving me crazy. 😢

**Comment by wholesomedev** [comment]
@forabi Maybe hold off on working on this one for now until you get a chance to focus on it :)

**Comment by forabi** [comment]
What I know so far is that it's completely random, the icon may or may not show each time I run the development server, but it never changes between working and broken until I restart the server again. I'll look into it later.

**Comment by forabi** [comment]
So this actually managed to leak to production. I rolled back to an earlier version from the AWS EB console.

**Comment by wholesomedev** [comment]
Should we reopen this since the latest attempt still doesn't fix it?

**Comment by wholesomedev** [comment]
Sorry, I misunderstood. Ignore the above comment.
