### ISSUE TITLE
A hard reload registers two browser history items

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#236]
As described in #225 

> When CORS is disabled, and I click on the "Reload" page button, the page registers two browser history items when it loads, so I can't back out of it without pressing the back button twice

**Comment by forabi** [comment]
This is no longer happening after refactoring handling of search box focus, and I think #289 is a totally different issue.

**Comment by forabi** [comment]
I'm not actually sure if this is fixed or not. I'm not able to reproduce this on hollowverse.com on Chrome, but I can reproduce in the development build.

**Comment by wholesomedev** [comment]
@forabi Yes, I also experienced in the development build early on.

**Comment by forabi** [comment]
Should be fixed in #290. Will test in production and report.

**Comment by forabi** [comment]
Looks like it's fixed. Please feel free to test and reopen if it's not.
