### ISSUE TITLE
iPhone input field focus causes zoom-in

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#237]
As described in #225 

> On iPhone, when user focuses an input field (e.g. search box or Facebook comments box), the page zooms in for no reason

**Comment by forabi** [comment]
From [an answer on StackOverflow](https://stackoverflow.com/a/6394497/1582641):

> The browser will zoom if the font-size is less than 16px and the default font-size for form elements is 11px (at least in Chrome and Safari).

I've set the input `font-size` to inherit from the parent in #230. I tested the change on Safari iOS.

**Comment by wholesomedev** [comment]
Does this fix the zooming for Facebook Comments box as well?
-- 
Sent from my iPhone

**Comment by forabi** [comment]
Nope. It looks like the Facebook comments plugin uses an `<iframe />`, so it cannot be targeted with CSS. It can be [styled with JS though](https://stackoverflow.com/questions/583753/using-css-to-affect-div-style-inside-iframe).

**Comment by wholesomedev** [comment]
@forabi Not sure if using JS to style the FB comments would be the best approach. Isn't there another solution to prevent the zooming, like perhaps by using a meta tag or something?

**Comment by forabi** [comment]
My first thought was to use `initial-scale=1.0, maximum-scale=1.0, user-scalable=0` for `<meta name="viewport" />` but it is generally regarded as a bad UX practice. Bootstrap no longer recommends this value. The user should be able to zoom in. We just want to disable the auto zoom-in behavior.

**Comment by wholesomedev** [comment]
@forabi On iOS Safari, the user can always zoom in, regardless of what values you set for `<meta name="viewport"/>`. But I don't know if the same is true for Android devices.

Regardless, why is it okay for native apps to not be zoomable but web apps have to be zoomable? I'm okay with disabling zooming if we can ensure that the app is still accessible the same way native apps are.

**Comment by forabi** [comment]
> why is it okay for native apps to not be zoomable but web apps have to be zoomable?

My thoughts too. Okay, so let's add `maximum-scale=1.0, user-scalable=0`.

**Comment by forabi** [comment]
> But I don't know if the same is true for Android devices.

Chrome respects the value of `<meta name="viewport"/>` so if we add `maximum-scale=1.0, user-scalable=0`, zoom will be disabled.

**Comment by forabi** [comment]
Fixed by #230
