### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#245]
This is what's currently being worked on in #230. As we discussed on Discord, we should add more logging to monitor user actions on our app.

**Comment by wholesomedev** [comment]
One thing we need to remember is to batch logging events. If log events happen in quick sequence, we should batch them and dispatch them in one HTTP request rather than multiple HTTP requests.

**Comment by forabi** [comment]
One thing I'd like to see logged is load and runtime performance metrics, using the [Navigation Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API) and custom performance markers with the [Performance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance)

**Comment by wholesomedev** [comment]
@forabi I thought about this some more and I'm beginning to think that maybe we *shouldn't* add logging proactively. Let's wait for us to have a need to log certain things and then we'll add logging for those.

If you're okay with this, let's close this issue.

**Comment by forabi** [comment]
Okay! :+1:
