### ISSUE TITLE
Implement content aware cropping for NP's image

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#247]
...so that we'll crop around the face area instead of the center because the current implementation is causing undesirable images such as the one for Michael Jackson.

**Comment by forabi** [comment]
Should this functionality be implemented as an AWS Lambda function or as part of the API codebase?

I'm wondering if assigning a URL for AWS Lambdas means they are effectively publicly accessible. If that's the case, anyone could send an image and have it cropped. I'll check if we can limit access to AWS Lambdas by VPC or if we can invoke it without assigning a URL.

**Comment by wholesomedev** [comment]
I think eventually we should have a Lambda that periodically updates NP information, like NP name, image, etc. Like determining the color palette, I feel cropping should happen once when we retrieve the image for the first time.

By the way, as I was browsing Hollowverse the other day, I noticed one NP that doesn’t have his face on the image. Instead the image is a picture of his distant silhouette standing on a concert stage. I wonder how content aware cropping would work for such a case.

**Comment by forabi** [comment]
> I think eventually we should have a Lambda that periodically updates NP information, like NP name, image, etc. Like determining the color palette, I feel cropping should happen once when we retrieve the image for the first time.

I feel cropping and extracting colors can still be part of the API codebase. I think the Lambda that updates the NP names can simply be a client of the API which uses the public GraphQL API to update a notable person, maybe something along these lines:

```graphql
mutation {
	updateNotablePerson(slug: "Tom_Hanks", patch: { wikipediaUrl: "https://...", wikipediaPhoto: "https://.." }) { }
}

```

... and the API takes care of updating the name and slug, cropping the photo and extracting the color palette.

That said, this surely requires some kind of role-based user authorization, so not every authenticated user can abuse the API to modify the database contents.

**Comment by wholesomedev** [comment]
@forabi Okay, how about this then...

We implement NP image upload in the API. Then in the future, when we build the Lambda that updates NP data (let's name it `np-wikipedia-update` Lambda for now), that Lambda would call the image upload end-point to upload the image.

At that point, we have two possible implementations for the rest of the process:

### Option no. 1

We create a Lambda called `face-crop` that watches an S3 bucket and crops any image that gets uploaded to that S3 bucket. The API would simply push the uploaded image to that S3 bucket and `face-crop` would take care of cropping.

### Option no. 2

`face-crop` doesn't watch an S3 bucket, but is rather called directly by the API.

So, when the API receives an image upload, the API would communicate with `face-crop` to get the image cropped and then the API would push the image to S3.

---

`np-wikipedia-update` is in our future roadmap. It's not really something we'll implement right away. For now, we need to crop the images that we already have. To do that, I think it might be possible to build `face-crop` and run it on all the image files that we have on S3. For new images, we can choose one of the implementations above, or something different entirely...

**Comment by forabi** [comment]
> To do that, I think it might be possible to build `face-crop` and run it on all the image files that we have on S3. For new images, we can choose one of the implementations above, or something different entirely...

I agree. We should implement this function first. I don't have a strong preference for one of the options above though, but I'm leaning towards watching the S3 bucket.

**Comment by wholesomedev** [comment]
I'll reopen this. We can then close it again when we start serving the cropped images in production.

**Comment by forabi** [comment]
This issue is now fixed and we are now serving the new images :tada:

**Comment by wholesomedev** [comment]
Awesome! The results look great! ✨
