### ISSUE TITLE
Lint against deeply nested code 

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#252]

**Comment by forabi** [comment]
#230 includes the `max-depth` rule for ESLint which works for TS and JS, we still need a rule for JSX/TSX, https://github.com/yannickcr/eslint-plugin-react/pull/1260 is not merged yet.

**Comment by wholesomedev** [comment]
@forabi Looks like https://github.com/yannickcr/eslint-plugin-react/pull/1260 is almost ready. It just needs rebasing and conflict resolution? Perhaps we can contribute that ourselves?

**Comment by forabi** [comment]
@wholesomedev Let's do that! 👍

**Comment by forabi** [comment]
I rebased the PR on upstream/master, waiting for guidance on how to submit the changes https://github.com/yannickcr/eslint-plugin-react/compare/master...forabi:max-depth

**Comment by forabi** [comment]
I just submitted the changes in a new PR https://github.com/yannickcr/eslint-plugin-react/pull/1676

**Comment by ljharb** [comment]
Rebasing doesn’t require assistance; collabs can do it on the author’s behalf.

**Comment by wholesomedev** [comment]
@ljharb Thanks! We just wanted to help and contribute to yannickcr/eslint-plugin-react#1676. Please let us know if there's anything we can do!

**Comment by forabi** [comment]
#313 added the required rule with the maximum allowed depth of 4. Should we limit the depth further?

**Comment by wholesomedev** [comment]
I was hoping this lint rule would lint against code such as [this](https://github.com/hollowverse/hollowverse/blob/master/src/app/pages/NotablePerson/NotablePerson.tsx#L156), which has 14 indentations 😅

**Comment by forabi** [comment]
Looks like what we need is TSLint's [`cyclomatic-complexity`](https://palantir.github.io/tslint/rules/cyclomatic-complexity/) or the equivalent ESLint `complexity` rule. ESLint also has `max-statements` and `max-nested-callbacks`.

**Comment by wholesomedev** [comment]
I just looked at the definition of [`cyclomatic-complexity`](https://palantir.github.io/tslint/rules/cyclomatic-complexity/) and I'm not sure it is what we need. We don't have a lot of nested cyclomatic complexity expressions in the example I linked to above.

Something like `max-statements` could perhaps suffice. Though, I see you disabled `max-func-body-length` in the example above 😄

**Comment by forabi** [comment]
We should have a rule to lint against disabled rules 😂. But what if I
disable that rule too? 🤔

wholesomedev <notifications@github.com> schrieb am Fr., 23. Feb. 2018, 1:53
vorm.:

**Comment by forabi** [comment]
> Though, I see you disabled max-func-body-length in the example above smile

#317 addressed this. I think this issue can now be closed.
