### ISSUE TITLE
Should we move server-side functionality of logging to an AWS Lambda?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#255]
In the spirit of having more of a micro-service architecture, I'm wondering if it would make sense for us to move the logging functionality that we've implemented in `server.ts` to a Lambda.

**Comment by forabi** [comment]
One issue I could see with this is accessing action types in the logging lambda. Currently the log endpoint knows the types of Redux actions in the app and we use them to transform those actions (like re-mapping the error locations to the source files). If we move logging to a lambda, would the lambda still be in this repo? If not, then we need to share the action types between two repos, keep the version in sync, and also account for differences between `beta` and `master`.

**Comment by wholesomedev** [comment]
> If not, then we need to share the action types between two repos, keep the version in sync, and also account for differences between `beta` and `master`.

That sounds challenging.

And if the Lambda is in this repo, then how would we deploy it separately? (I still don't know how projects manage CI tasks in a mono-repo.)

**Comment by forabi** [comment]
> And if the Lambda is in this repo, then how would we deploy it separately? (I still don't know how projects manage CI tasks in a mono-repo.)

We need to convert this repo to a mono repo, or have a sub-project (separate `package.json` and different compilation settings, because Lambdas only supports Node 6 and 4!)

**Comment by wholesomedev** [comment]
> We need to convert this repo to a mono repo, or have a sub-project (separate package.json and different compilation settings, because Lambdas only supports Node 6 and 4!)

I don't know the right (i.e. best) way to do these things.

(Ah, bummer that Lambda is stuck on older Node versions!)

**Comment by forabi** [comment]
Now that I've worked with Lambda, I think we should move logging to Lambda. I'm just trying to find a way that keeps the development workflow as convenient as possible.

We have to make the function compatible with both `master` and `beta`, and we want to make sure that no changes to the function can break logging for already-deployed versions.

Maybe we can clone `master` and `beta` branches when building the function and check that the function is compatible with all the types from both branches? This is similar to what we are doing for the API.

**Comment by wholesomedev** [comment]
@forabi now that hollowverse.com is being served from AWS API Gateway/Lambda, do you think there's more benefit to be gained from further separating out the logging functionality into its own Lambda?

**Comment by forabi** [comment]
@wholesomedev I think it's something that's nice to have (smaller functions that each does one thing are always better) but it might be tricky to implement with our current dev setup because we don't have a way to simulate API Gateway and thus we can't test things locally. I think we should first decide how to proceed with #424.
