### ISSUE TITLE
Adjust layout to be more like an app and less like a website

### ISSUE THREAD

**Issue by deltaidea** [hollowverse-archive/hollowverse#26]
If we're doing the whole web app thing, the layout should follow web app patterns:

![Current layout](https://cloud.githubusercontent.com/assets/4950036/24831623/d5527b0a-1cb6-11e7-9f0a-3af1e83793a2.png)

See [Designing Great UIs for Progressive Web Apps](https://medium.com/@owencm/designing-great-uis-for-progressive-web-apps-dd38c1d20f7) for more details.

> Take UX inspiration from native apps

**Comment by wholesomedev** [comment]
👍

**Comment by wholesomedev** [comment]
This is also done I think. Closing...
