### ISSUE TITLE
Cursor is sometimes out of search box when loading search page

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#288]
I don't know the exact steps to reproduce this consistently but one possible way is to:

1. open Safari iOS
1. open https://hollowverse.com/Tom_Hanks in Private Browsing mode
1. Scroll down a few folds
1. Tap on the search field

**Screenshot attached.**

![image](https://user-images.githubusercontent.com/26730388/35783506-418c72d2-09bd-11e8-9e63-b24d9b2f2524.png)

**Comment by forabi** [comment]
Looks like it's a Safari bug that we'll need to work around somehow.

**Comment by wholesomedev** [comment]
The navbar behavior in Safari iOS is very problematic. I think the top and bottom navbar expanding and contracting behavior is contributing to this issue.

Based on my quick tests, if you tap on the search field while the top navbar is expanded, then you don't get this problem. But if you tap on the search field while the top navbar is contracted, then you get this problem.

Another inconsistency that the navbar is causing is with the 'scroll to top' functionality that we've recently implemented. The page doesn't scroll all the way to the top because of the expanding/contracting navbar. You can test this by tapping on one of the "other interesting profiles" while the top navbar is expanded and another time while it's contracted. You'll see that when you do it while the navbar is expanded, the page scrolls to the top correctly. When you do it while the navbar is contracted, the page scrolls to the top correctly, but then the top navbar expands and covers a small portion of the top.

I feel we should disable this top navbar behavior. I don't think there's a flag or such to disable it, but if we write our HTML/CSS in a certain way, it is possible to disable it. For example, the way Google's Accelerated Mobile Pages are built disables this behavior ([example](https://www.google.com/amp/s/amp.cnn.com/cnn/2018/02/05/politics/donald-trump-stocks-ohio-tv/index.html)). I think we should also build our HTML/CSS to disable this behavior.

**Comment by forabi** [comment]
>  top navbar 

Just to make sure I understand correctly, by "top navbar"" you are referring to the address bar of Safari, right?

> You can test this by tapping on one of the "other interesting profiles" while the top navbar is expanded and another time while it's contracted. You'll see that when you do it while the navbar is expanded, the page scrolls to the top correctly. When you do it while the navbar is contracted, the page scrolls to the top correctly, but then the top navbar expands and covers a small portion of the top.

I'm not able to reproduce this. I see the correct behavior ([as you can see here](https://www.dropbox.com/s/jwrackivpn5ycg9/File%2006-02-2018%2C%204%2012%2005%20PM.mov?dl=0)) in both cases and the navbar does not expand automatically when the page scrolls to top. What's your version of Safari?


> I feel we should disable this top navbar behavior. I don't think there's a flag or such to disable it, but if we write our HTML/CSS in a certain way, it is possible to disable it. For example, the way Google's Accelerated Mobile Pages are built disables this behavior (example). I think we should also build our HTML/CSS to disable this behavior.

Interesting. Looks like [this is how it's done](https://stackoverflow.com/questions/29894997/prevent-ios-bounce-without-disabling-scroll-ability). I've added this workaround in #290, although I had to explicitly enable momentum scrolling for `body` because scrolling was too slow without it.

**Comment by forabi** [comment]
Re-opening as the fix in #290 introduced another issue in Safari.

**Comment by wholesomedev** [comment]
> I'm not able to reproduce this. I see the correct behavior ([as you can see here](https://www.dropbox.com/s/jwrackivpn5ycg9/File%2006-02-2018%2C%204%2012%2005%20PM.mov?dl=0)) in both cases and the navbar does not expand automatically when the page scrolls to top. 

Hmm, not for me 🤔

https://cdn.discordapp.com/attachments/308394051114237952/410626571242569728/ScreenRecording_02-06-2018_17-17-37.MP4

> What's your version of Safari?

Not sure. I just updated iOS today, so the latest 😅

**Comment by forabi** [comment]
So #290 successfully disabled the Safari navbar animation [using the most commonly used technique](https://stackoverflow.com/questions/19830273/over-riding-the-bottom-and-top-touch-area-on-ios7-safari-landscape), but that introduced an issue that caused the page to be stuck as described in #291. So far I've tried [a few](https://www.npmjs.com/package/ios-inner-height) [different](https://stackoverflow.com/questions/32897960/ios-9-webkit-overflow-scrollingtouch-and-overflow-scroll-breaks-scrolling) [workarounds](http://patrickmuff.ch/blog/2014/10/01/how-we-fixed-the-webkit-overflow-scrolling-touch-bug-on-ios/) (including using pixel units to set the body height, as is done one the [CNN AMP page](https://www.google.com/amp/s/amp.cnn.com/cnn/2018/02/05/politics/donald-trump-stocks-ohio-tv/index.html)) but none seem to do the trick. I suspect that having a sticky header at the top is somehow contributing to the problem.

**Comment by forabi** [comment]
I've created a [JSBin with the minimum amount of code required to disable the navbar animation](http://jsbin.com/lehofawula/8/edit?css,js,output), and it seems that I was wrong about the sticky header contributing to the bug. It looks like just disabling the navbar triggers the bug.

**Comment by forabi** [comment]
[This JSBin](http://jsbin.com/3/ixewok/10/) by Remy Sharp, from 6 years ago, exhibits the same issue. It shows the values for `window.pageYOffset`, `body.scrollTop`, `window.scrollY` at the top of the page respectively, and it confirms my suspicion that Safari is getting confused on what element to scroll: the window or the body (in the case of the linked JSBin). The first and third values displayed in the green bar at the top of page change when the bug is triggered, which indicates that it's the `window` element that is being scrolled, while the second value stays at `0`, which means `body` is not being scrolled.

However, the issues Remy Sharp [was trying to debug](https://remysharp.com/2012/05/24/issues-with-position-fixed-scrolling-on-ios), in... Safari 5, seem to be irrelevent.

**Comment by wholesomedev** [comment]
As I was looking at our search page today, I decided to take a stab at this issue. Basically, I wasted a lot of time with nothing to show for it. Then as I was brushing my teeth and getting ready to go to bed, I remembered that I read on twitter recently that the AMP project is open source: https://github.com/ampproject/amphtml

I took a brief look through the repo and the related websites, I couldn't right away find an example of the technique that disable's COMB's dynamic bars.

Anyway, this is a good reference to keep around for when we decide to tackle this issue again. Also, this AMPHTML open source project seems interesting.

**Comment by wholesomedev** [comment]
Here it is: https://github.com/ampproject/amp-viewer 
AMP Viewer is responsible for rendering AMP pages. I managed to build it and try it out. It does disable COMB's dynamic bars. I tried to find out how it does it but found iframes and stuff...

(To build the project and get it to run, a `require` statement to a missing dependency needs to be edited)

**Comment by forabi** [comment]
Good to know! It's definitely worth looking into. Last time I took a stab at this I suspected that the `iframe` used in AMP might be hiding the scrolling issue in Safari.

**Comment by wholesomedev** [comment]
@forabi If the solution does indeed require putting our content in an `iframe`, that would mean that this solution is out of the question. I don't think we should have an `iframe` as the top level element of our client app. I don't know what issues may arise from doing that, but I have a suspicious that issues _will arise_ if we did something unusual like this.

...so we'll have to either change our UX, or find some other workaround...

One thing I noticed as I was testing yesterday is that COMB doesn't obey `position: sticky` when the keyboard is out. While the keyboard is out, every thing scrolls.

**Comment by forabi** [comment]
> If the solution does indeed require putting our content in an iframe, that would mean that this solution is out of the question.

Good call. `iframe` will bring too many issues that we better find an alternative solution.

> One thing I noticed as I was testing yesterday is that COMB doesn't obey position: sticky when the keyboard is out. While the keyboard is out, every thing scrolls.

Not sure I understand?

**Comment by wholesomedev** [comment]
>> One thing I noticed as I was testing yesterday is that COMB doesn't obey position: sticky when the keyboard is out. While the keyboard is out, every thing scrolls.
>
>Not sure I understand?

When you're on the search page, the search box is in focus, and the keyboard is out, you may expect the search box to remain in view even if there are search results that can be scrolled through (since the search box is sticky). That, however, is not what happens. The search box, when the keyboard is out, is not sticky anymore. It scrolls out of view with everything else. It becomes sticky again when the keyboard is dismissed. Even on the NP page, if you focus the FB comments input field, the navbar loses its stickiness.

**Comment by forabi** [comment]
I see. Technically we are not using `position: sticky` (I mean the CSS property), we are emulating that by toggling `position: static` and `position: fixed`. I believe this may be sorted out when we disable Safari's address bar behavior.

**Comment by wholesomedev** [comment]
@forabi It's the same with `position: sticky`. It's ignored when keyboard is out. I tried that yesterday. 

There are several factors that contribute to this problem: 

1. scroll to top on route load
1. position stickiness
1. COMB's dynamic bars
1. some other unknown factors probably...

**Comment by wholesomedev** [comment]
@forabi I just tested this in the latest iOS Safari and I’m no longer able to reproduce the issue? Did it somehow get fixed? I’m in disbelief!

**Comment by forabi** [comment]
@wholesomedev I just tested again and I'm not able to reproduce. I don't feel very confident closing this because it's, well, Safari. But I'm just going to close it anyway :laughing:
