### ISSUE TITLE
Navigating back to NP page from Search page sometimes doesn't work

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#289]
If I use iOS Safari swipe gesture to navigate back to an NP page after being on the search page, what ends up happening is that the search page will reload.

Here's how to reproduce:

1. open Safari iOS
1. open https://hollowverse.com/Tom_Hanks in Private Browsing mode
1. Scroll down a few folds
1. Tap on the search field
1. Swipe (or use the back button) to go back to the NP page

**What should happen?**

Go back to the NP's page.

**What actually happens?**

The search page reloads.

I think what's happening is that pressing on the search field or the search icon causes two Search page items to be loaded in the browser's navigation history...or something weird like that. So this might be related to #236

**Comment by forabi** [comment]
Confirmed. Safari only.

**Comment by forabi** [comment]
Closed by #290
