### ISSUE TITLE
Fix deprecation warning that shows when running webpack commands

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#29]
![](https://i.imgur.com/5cvA0r8.png)

**Comment by wholesomedev** [comment]
I looked into this warning, and read the linked GitHub issue https://github.com/webpack/loader-utils/issues/56. It looks like one of our webpack loaders is the culprit. I tried to trace it, but couldn't easily find out which one. I think if we wait and keep our dependencies up to date, it'll get fixed.

**Comment by deltaidea** [comment]
Yep, as the name `loader-utils` would suggest, some loader isn't up to date with its API usage.
