### ISSUE TITLE
Logout functionality doesn't work on x.hollowverse.com

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#30]
![recording](https://cloud.githubusercontent.com/assets/26730388/24832831/8aedb6ea-1c6d-11e7-9ecc-d18797baf441.gif)

**Comment by forabi** [comment]
@msafih Is this still relevant? I don't see any login/logout functionality in UI.

**Comment by wholesomedev** [comment]
Hmmm, I guess not really since we've dropped logging in/out from our immediate requirements. I'll close this one out.
