### ISSUE TITLE
Should we hook up greenkeeper.io?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#31]
https://greenkeeper.io/

Basically, it'll keep our dependencies up to date, always. I think it's a good idea to set it up.

Thoughts @deltaidea?

**Comment by deltaidea** [comment]
This is awesome! Why haven't I heard of them! [Install!](https://github.com/integration/greenkeeper)

**Comment by wholesomedev** [comment]
This is done!
