### ISSUE TITLE
Fix and improve development setup

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#320]
So having some time to kill I thought I'd take a stab at recombining the NP page code, so I went through the [development workflow](https://github.com/hollowverse/hollowverse/wiki/Web-App-Development). 

I used 

```
docker-compose up --build
```

and a bunch of text started scrolling up my terminal. At the end of it, I saw 

```
web_app_1  | [remotedev            ] --------------------------------------------------------------------------------
web_app_1  | [remotedev            ]
web_app_1  | [remotedev            ]    [Busy] Launching SocketCluster
web_app_1  | [remotedev            ]    [Active] SocketCluster started
web_app_1  | [remotedev            ]             Version: 6.8.0
web_app_1  | [remotedev            ]             Environment: dev
web_app_1  | [remotedev            ]             WebSocket engine: uws
web_app_1  | [remotedev            ]             Port: 8000
web_app_1  | [remotedev            ]             Master PID: 1545
web_app_1  | [remotedev            ]             Worker count: 1
web_app_1  | [remotedev            ]             Broker count: 1
web_app_1  | [remotedev            ]
web_app_1  | [app/graphql/dev      ] $ export API_ENDPOINT=${API_ENDPOINT:-https://api.hollowverse.com/graphql}; apollo-codegen introspect-schema ${API_ENDPOINT} --output ./graphqlSchema.json
web_app_1  | [app/graphql/dev      ] $ apollo-codegen generate 'src/app/**/*.{graphql,gql}' --target typescript --output src/app/api/types.ts
web_app_1  | [server/app-server/dev] Starting webpack compilation...
web_app_1  | [server/app-server/dev] [HPM] Proxy created: /  ->  https://api.hollowverse.com/graphql
web_app_1  | [server/app-server/dev] webpack built 819556f48bd66cf9e816 in 42534ms
web_app_1  | [server/app-server/dev]
web_app_1  | [server/app-server/dev] webpack: Compiled successfully.
web_app_1  | [server/app-server/dev] App server is listening on port 3001
```

I thought good, now I can load the app at `http://localhost:3001`, but unfortunately nothing turned up there. I got

![image](https://user-images.githubusercontent.com/26730388/36636022-d56773d4-1972-11e8-9d75-8f7df8c668d3.png)

So I tried

```
yarn start
```

but that complained that `dist/mainServer.js` is missing, so I figured this command is probably for starting the deployed application. So I tried

```
yarn dev
```

With `yarn dev`, things seemed to work. I loaded `http://localhost:3001`. At least now I was getting:

```
Error: ENOENT: no such file or directory, open '/some/path/hollowverse/secrets/sumo.json'
```

So I added a dummy `sumo.json` file with `{}` as content to the path where it was expected, and restarted the server and loaded `http://localhost:3001` again. This time I got

```
Cannot GET /
```

Finally, I tried `http://localhost:3001/Ray_J` and got a page to load 🎉

We should try to streamline development setup for a new machine.

**Comment by forabi** [comment]
Yeah, the development setup needs a lot of work. But the docker-compose issue seems strange. I set up my new laptop a few weeks ago and the first thing I did was starting the docker-compose container and it worked.

**Comment by wholesomedev** [comment]
@forabi Yeah, it's an interesting outcome to have docker say that the server is listening at 3001 and yet there's nothing there. Not sure what's happening there...

Another improvement that I'd like to suggest is allowing the page to load despite lint errors, like this:

![image](https://user-images.githubusercontent.com/26730388/36636177-cc8aa1fc-1975-11e8-8148-76f9bf5d9197.png)

These are only a couple of lint errors, I don't think it's a good idea that they should block development.

**Comment by forabi** [comment]
BTW I'm not sure `docker-compose` can be very useful for contributors, they will still need `git` installed, and if they want to commit something, the git hooks we are using depend on node.js and many of our `devDependencies`. It might still be useful for someone who just wants to take a quick look at the code and test a few changes though.

**Comment by forabi** [comment]
> These are only a couple of lint errors

These are TypeScript compilation errors. We do not do any linting during development. The code will literally not compile if TypeScript throws an error.

**Comment by wholesomedev** [comment]
@forabi 

> BTW I'm not sure docker-compose can be very useful for contributors, they will still need git installed, and if they want to commit something, the git hooks we are using depend on node.js and many of our devDependencies. It might still be useful for someone who just wants to take a quick look at the code and test a few changes.

Agreed. I'm in favor of removing `docker-compose` from development setup.

> These are TypeScript compilation errors. We do not do any linting during development. The code will literally not compile if TypeScript throws an error.

If I remember correctly, TypeScript introduced a configuration option to let it compile even if there are errors.

**Comment by forabi** [comment]
> If I remember correctly, TypeScript introduced a configuration option to let it compile even if there are errors.

It is possible, and we actually have a flag for this (`NO_TYPE_CHECK=1`), but I think that throwing immediately might be a better option. Otherwise, errors will accumulate and they will become harder to track down during development.

**Comment by forabi** [comment]
A better approach might be to relax some of TypeScript options in development, like `noImplicitAny`, `noUnusedLocals`... etc.

**Comment by wholesomedev** [comment]
@forabi I'm fine with the current setup since there's an option (i.e. `NO_TYPE_CHECK=1`) to disable type-checking if one wants to quick-and-dirty try things.

I just tried `NO_TYPE_CHECK=1 yarn dev` and it seems to be doing what I need.

**Comment by forabi** [comment]
Cool!

**Comment by wholesomedev** [comment]
With #425 in the works, there's no actionable items in this issue. Closing...
