### ISSUE TITLE
"Loading..." text flashes on non NP pages

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#323]
How to reproduce:

1. Go to https://hollowverse.com/Tom_Hanks
1. Position your cursor on "Hollowverse" logo in the navbar
1. While keeping your eye on the top-left corner of the viewport, click on "Hollowverse" logo in the navbar

You will see "Loading..." text flashing in the top left corner of the view port under the navbar.

**Comment by forabi** [comment]
We need to use either a generic loading component or a skeleton for the home and text pages
