### ISSUE TITLE
Consider a more robust architecture for track-performance

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#327]
AWS Lambdas have a maximum execution time of 5 minutes. We currently request a test to be performed on WebPageTest and wait for the results in the same function. This works fine if we get the results within 5 minutes, but a more robust architecture would involve splitting the code into two functions: one that triggers requests to external services (like WebPageTest) and another one that listens for incoming HTTP requests to collect the reports. WebPageTest can be configured to `POST` to a specific endpoint when the test results are ready. This also means that we will have to keep some state between function runs somewhere outside AWS Lambda, probably in a key-value store like Redis or DynamoDB.

**Comment by wholesomedev** [comment]
I'm not sure this is worth implementing, might be high difficulty low impact at this time...

**Comment by forabi** [comment]
Yeah, I was going to suggest that. The function has been working fine since we first deployed it, even with many URLs being tested by WPT concurrently. This is a nice-to-have thing but not a top priority.

**Comment by forabi** [comment]
I'm going to close this. I don't think we will ever need to do it.

**Comment by wholesomedev** [comment]
👍
