### ISSUE TITLE
Hot Loader errors in console

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#339]
Sometimes I these errors in console

![image](https://user-images.githubusercontent.com/26730388/36951393-30c45af8-1fb8-11e8-982c-dbcbfccbd959.png)

Can we do something about these errors? Can we configure Hot Loader to reload the page when it fails to hot reload content?

**Comment by forabi** [comment]
`react-hot-loader` does not like having more than one component per file. We should first upgrade to v4 and see what should be done to fix this.
