### ISSUE TITLE
Automatically merge perf-reports PRs

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#344]
Make Hollowbot automatically merge `perf-reports` PRs

**Comment by forabi** [comment]
This was already implemented in https://github.com/hollowverse/perf-monitor/commit/69a8972a3bd47490952040b617ffb4542bc88080 https://github.com/hollowverse/perf-monitor/commit/77843547e0a5483dd78d718099b4bfc564498498

**Comment by forabi** [comment]
Looks like something is wrong with merge code.

**Comment by forabi** [comment]
This should hopefully be fixed with https://github.com/hollowverse/perf-monitor/pull/14, but I'll wait for today's report before closing this.
