### ISSUE TITLE
Buggy padding on related people

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#349]
![da28487a-7f23-4670-b352-adae6748d59b](https://user-images.githubusercontent.com/26730388/37191257-4bdda0c0-2313-11e8-8f1d-bc77a1446ab8.png)

**Comment by forabi** [comment]
Should cards all be of the same height even when one has overflowing text?

![screenshot from 2018-03-09 15-55-05](https://user-images.githubusercontent.com/1012761/37210780-945b5cd0-23b2-11e8-8256-78bb195cf4e5.png)

or should it be like this?

![screenshot from 2018-03-09 15-54-45](https://user-images.githubusercontent.com/1012761/37210781-94a8f3d2-23b2-11e8-884a-e4c42165419d.png)

**Comment by wholesomedev** [comment]
@forabi I think the second one looks better, but can we use something like flexbox `align-items: center;` to align the names in the center of the whitespace?
