### ISSUE TITLE
Add meta description tag to Hollowverse pages

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#357]
We should add meta description tag to the Hollowverse pages, such as Notable Person, Search, and Homepage.

**Comment by forabi** [comment]
What should the `content` for each page be? We already have "Religion, politics and ideas of the influentials" in the homepage title and "NP's Religion and Political Views" for the NP page. For the search page, we can add "Search for influential people"

**Comment by wholesomedev** [comment]
@forabi For the homepage, we can leave it as is. For the NP page, we can have a description tag as "Quotes, news, and discussions about Tom Hanks's philosophy, politics, and ideas". For the search page, we can do "Search for an influential person to find out about their philosophy, politics, and ideas".
