### ISSUE TITLE
Handle UX of NP without image in search results list

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#364]

**Comment by forabi** [comment]
For reference, here's what the page looks like if an NP has no image:

![localhost_3001_search_query democrat nexus 4 1](https://user-images.githubusercontent.com/1012761/37705246-0f7fe19c-2d04-11e8-97ed-d02722f5a74f.png)

**Comment by forabi** [comment]
We can make the background of the image transparent and add a border:

![localhost_3001_search_query cash nexus 4](https://user-images.githubusercontent.com/1012761/37705469-cf364e9a-2d04-11e8-8c39-450cee27f01a.png)

**Comment by wholesomedev** [comment]
@forabi I don't think that's an ideal solution. Maybe we should show a gender-neutral placeholder avatar?
