### ISSUE TITLE
Another idea for easily sharing and synchronizing setup/config between repos

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#366]
Okay, so I was once again thinking about an easy way to share configurations. I reviewed the [last discussion we had on the topic](https://github.com/hollowverse/common/pull/25). Based on that discussion, I got a few ideas. Allow me to share them...

## The problem

We have a bunch of configuration files spread over many repos. The configurations can easily get out of sync, which makes things harder to maintain. Moreover, it's annoying to setup a repo from scratch.

## The solution

A new tool that copies configuration from **another repo** and brings those configurations to your **current repo**. It does that by simply doing a deep merge of files, file contents, and directories. If it finds a conflict, it complains (unless you have explicitly used the escape hatch).

Let's call this new tool hvc for Hollowverse Configurator.

## How it would work

Say we want to use hvc to setup `hollowverse/hollowverse` based on `hollowverse/common`. Here's how that would work:

In `hollowverse/hollowverse` some of the technologies we need are TypeScript, React, and GraphQL. For each one of these technologies, we have certain dependencies, npm scripts, configuration files, linting rules, and more.

So what we can do in `hollowverse/common` is have the following directory structure

```
|-- typescript
|   |-- package.json
|   |-- tslint.json
|   |-- tsconfig.json
|   |-- eslintrc.json
|
|-- react
|   |-- package.json
|   |-- eslintrc.json
|
|-- graphql
|   |-- package.json
|   |-- eslintrc.json
```

Each directory in `hollowverse/common` will correspond to the requirements of a certain workflow or a technology. 

The contents of the files in each directory can be fragments of configurations that are relevant to the workflow or technology. For example, `hollowverse/common/typescript/package.json` maybe nothing more than:

```json
{
  "devDependencies": {
    "tslint": "^5.9.1",
    "typescript": "^2.7.2",
  }
}
```

Then in `package.json` of `hollowverse/hollowverse`, we can have the following:

```json
"hvc": {
  "package": "@hollowverse/common",
  "directories": ["typescript", "react", "graphql"]
}
```

Now when you run hvc, first hvc will look at what the source `package` is. In this case it is `@hollowverse/common`. Then it will look at what the directory names are. In this case they are `typescript`, `react`, and `graphql` (in that order).

Now hvc will merge the content of `hollowverse/common/typescript/package.json` with `hollowverse/hollowverse/package.json`. Then it will merge the content of `hollowverse/common/typescript/tslint.json` with `hollowverse/hollowverse/tslint.json`. It will continue doing the same for the rest of the files in `hollowverse/common/typescript`. Then it will move to `hollowverse/common/react` and perform the same merging operation. If there are conflicts between the source directories, the later values will win.

## How to override configurations

hvc will complain if you have existing configurations that don't match the configurations from your latest source directory. So how do you override certain values?

We can come up with many solutions for escape hatches, but here's one suggestion:

You can create a local directory `.hvc` in your repo. This directory will be considered the last source of configurations. Its contents will be merged with the rest of the configuration files in your repo and overwrite any existing values.

## Ensuring consistent configurations

hvc can have a task that throws if it sees that your local configurations are different from your source configurations. We can run such task as the prepush hook and on the CI.

## What it all means

We will no longer extend stuff from `hollowverse/common`. Instead the contents of `hollowverse/common` will be literally copied to `hollowverse/hollowverse`.

hvc will be able to merge the contents of any configuration file with a simple structure, like JSON and YML. It should also be possible to merge `.ignore` files. I think that should cover most cases? For other types of files that we want to share, such as `js` or `ts`, we can make hvc simply copy the whole content without attempting to merge anything.

What do you think? Do you foresee any major issues or should I try building it?

**Comment by forabi** [comment]
Just the other day, I came across a new tool that I think can solve our configuration sharing issues completely, but I can't for the life of me remember its name. I went through my Chrome history for the last couple days but I couldn't find it. Was I dreaming of an imaginary tool? :sweat_smile:

**Comment by wholesomedev** [comment]
Dude, that’s a cruel joke! 😝

**Comment by forabi** [comment]
I swear I wasn't dreaming :rofl:. But I really can't find it now. It had a weird name that does not indicate what it does. Searching on GitHub didn't help.

**Comment by forabi** [comment]
Here it is! https://github.com/milesj/beemo

Told you I was not dreaming!

**Comment by wholesomedev** [comment]
@forabi This looks interesting, but it's in the same category as https://github.com/FormidableLabs/builder

What I don't like about these tools is that they are "wrappers". Wrapping around build and development tools is more likely to lead to problems. It also adds yet another layer that contributors have to learn.

What I proposed above is different. It's much less intrusive. It doesn't hide anything. It works very much like if you were to manually copy/paste configurations, except it allows you to copy/paste everything with one command.

**Comment by forabi** [comment]
Your suggestion makes a lot of sense, but I'm afraid that merging configurations is not going to be that simple. We may need logic specific to each technology to do the merging. It's an interesting solution and I think we should give it a try.

**Comment by forabi** [comment]
And I completely agree with you that "wrappers" will introduce more complexity. Every single tool that wraps something else will end up being a leaky abstraction.

**Comment by wholesomedev** [comment]
So I started working on this and your hunch was correct. Merging configurations with their many different structures is not that simple. One way to solve this is to create a specific merging function for each configuration type. But I don't like that solution because I feel there could be a better approach.

I feel that by using some heuristics, it might be possible to correctly merge the different types of configurations for most cases.

I'll be working on this as time allows, and I'll see how it goes 😄
