### ISSUE TITLE
Switch back to @babel/preset-env when babel-preset-minify is stable

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#368]
`babel-preset-minify` is still buggy, we had to switch to ES5 and UglifyJS. We should switch back to using `@babel/preset-env` and `babel-preset-minify` when the latter becomes stable.

**Comment by wholesomedev** [comment]
Now that we've reverted the change, what should we do with this issue?

**Comment by forabi** [comment]
Maybe we should just close it, we can open it later.
