### ISSUE TITLE
Remove code from `hollowverse/common`

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#373]
I think it wasn't a good idea to use `hollowverse/common` for more than just config. I think we should create a separate repo for sharing common utility code. 

I suggest we move code out of `hollowverse/common` to another repo called `hollowverse/utils` (or something...), and we rename `hollowverse/common` to `hollowverse/common-config` or `hollowverse/config` (or something...) and reserve it for configuration purposes only.

Thoughts?

**Comment by forabi** [comment]
Done!

**Comment by wholesomedev** [comment]
🚀
