### ISSUE TITLE
Search used to work without JS, now it doesn't

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#379]
I just noticed that the search page with JS disabled is always empty, even when I type a query and submit the form. This is a regression.

**Comment by forabi** [comment]
Turns out this is not an issue with our code. It's because we haven't whitelisted the `query` parameter on the search page.

**Comment by forabi** [comment]
I've updated the CloudFront distribution settings to forward all the query string parameters and cache based on all as well. The change fixes this issue.

**Comment by wholesomedev** [comment]
👍
