### ISSUE TITLE
Allow Clown CLI to execute a callback function per extension folder

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#389]
This would give a lot of flexibility to extension folders to allow them to do some post-processing.

The main problem with this approach is that it would break the `clown check` functionality. The way to fix this would be to make clown check use a fully mocked file system, which is something that has not worked very well for me when I tried it.

**Comment by forabi** [comment]
I was going to sleep, but I just had this weird idea and I couldn't help but share it :smile: 

What if we use [Node.js `vm` module](https://devdocs.io/node/vm) to create an isolated JavaScript context to execute the callback function? That way we can limit what the function can do and even provide our own utility functions to be used in `clown.js`.

Here is a basic implementation:

```typescript
const vm = require('vm');
const fs = require('fs');
const sandbox = {
  deleteFile: async (path) => { await fs.unlink(path); }
};
vm.createContext(sandbox);

const code = '<read clown.js as a string>';
vm.runInContext(code, sandbox);

```

We could easily mock `deleteFile` for dry runs (i.e. `clown check`).

**Comment by forabi** [comment]
The callback code could be as simple as:

```js
deleteFile('/path/to/file');
```

**Comment by wholesomedev** [comment]
@forabi what's the benefit of using `vm` here? Wouldn't this be the same as passing a `sandbox` object as an argument to the `clown.js` callback function?

**Comment by forabi** [comment]
> Wouldn't this be the same as passing a sandbox object as an argument to the clown.js callback function?

If we just pass this object, the callback code and still do this:

```js
const fs = require('fs');

fs.unlink('path/to/file');

```

So the "sandbox" is not really doing anything, it can easily be escaped. With `runInContext`, `require` is not even defined in the function's context. Think of it like how workers cannot access the DOM in the browser. It's an entirely different environment, the only thing in common is that it uses JavaScript as the language.

**Comment by wholesomedev** [comment]
@forabi Oh, I see. That's interesting. 

Yeah, this could be a viable solution. It would limit what the callback functions can do though, maybe too much. 

Passing arguments to the callback functions gives responsibility to the callback function, which is not ideal either.

If we can get a mocked filesystem to work properly during dry-runs, that would be ideal I think.

**Comment by forabi** [comment]
> It would limit what the callback functions can do though, maybe too much

Yes, that's true.

**Comment by wholesomedev** [comment]
I got an idea about this one. I should've thought of this earlier! 😅

clown builds an in-memory JavaScript object of files and file contents for each extension folder. The callback function of the extension folder can receive this in-memory JavaScript object and manipulate it and return it back to clown to be written to disk. That way the consumer doesn't have to work with the filesystem. They can work with a JavaScript object.

**Comment by forabi** [comment]
Nice!
