### ISSUE TITLE
Use semantic-release for publishable packages

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#390]
As discussed, we're going to introduce semantic-release for publishable packages.

Apparently, SR also handles creating a changelog for us based on the commit messages. Here's the flow I established so far, let me know what changes you think we need to make:

All commits in publishable packages have to follow this format `type: message`. `type` can be `Fix`, `Feature`, `Breaking`, or `Other`. 

`Fix`, `Feature`, and `Breaking` will appear in the changelog. `Other` won't. `Fix` will affect `patch`, `Feature` `minor`, and `Breaking` `major`. `Other` won't affect semantic version.

`Other` is for things like updating the docs, testing, CI fixes, etc.

However, even though this commit style is enforced through [commitlint](https://github.com/marionebl/commitlint) in our publishable packages, when we use Squash Merge of GitHub, these commits don't make it to master, so they don't really  get analyzed by SR. What ends up becoming the commit message, which gets analyzed by SR, is the value of the first input field in this image:

![image](https://user-images.githubusercontent.com/26730388/38461855-fa61b382-3a8f-11e8-83ef-2d7f0f4b4e55.png)

Unfortunately, there's no way to enforce a commit style in this field. We'll just have to remember to use the `type: message` style in this field.

And hopefully with commitlint enforcing this style in regular commits, we'll be more likely to remember 😄

**Comment by wholesomedev** [comment]
So I just spent like 3 hours trying to figure out how to configure semantic release to generate a changelog. It turns out I needed to add some cryptic values to some JSON object to get it to work.

Since every PR in our publishable packages is going to be a release, that means each changelog is going to have just one commit.

**Comment by forabi** [comment]
Should we close this?

**Comment by wholesomedev** [comment]
@forabi Yeah, if the way we're using semantic-release seems fine to you, we can close this one.

**Comment by forabi** [comment]
Seems fine to me :+1:
