### ISSUE TITLE
Add instructions for how to run hollowverse/api tests

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#398]
I was just working on hollowverse/api and wanted to test things by running `yarn test`. The command didn't pass because it couldn't find the right servers to connect to? Should we add docs about this some where or make `yarn test` launch the required servers?

**Comment by wholesomedev** [comment]
Or would it be possible to mock those servers in the same Node process so that no connections to outside servers is required for the tests?

**Comment by forabi** [comment]
I'm on mobile right now but you can launch a MySQL container using the same
first docker run command in .travis.yml (just replace --link database with
--network host). We should explain this somewhere.

**Comment by forabi** [comment]
Just to clarify, there are no "outside servers" used for tests. We only need a local MySQL instance on port 3306, whether native or in a container.

**Comment by forabi** [comment]
Should be fixed with https://github.com/hollowverse/api/pull/79

**Comment by wholesomedev** [comment]
@forabi Thanks for fixing this!

By outside server I meant a server that is running outside of the Node process where the tests are getting executed. In other words, I'm asking if it would be better to mock the database instead of having an actual database for the tests? Anyway, this is not urgent. Just something to consider for the future.

**Comment by forabi** [comment]
I actually tried using an in memory SQLite database (not MySQL) because
it's simpler to set up but that didn't work because SQLite does not support
some of the column types used. I don't think it's a good idea to use a
different database engine anyway. With Docker we can get a server that's
very close to the production database.

**Comment by wholesomedev** [comment]
Sounds good, thanks! 👍
