### ISSUE TITLE
Reset version to 0.1.0?

### ISSUE THREAD

**Issue by deltaidea** [hollowverse-archive/hollowverse#4]
`package.json` currently has `version` set to 1.0.0 which suggests that we have a stable release.

> **How should I deal with revisions in the 0.y.z initial development phase?**
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.
>
> — [semver.org](http://semver.org/)

@msafih, what do you think? I'd say, let's switch back to 0.1.0 while no one cares and follow semver from now on.

**Comment by wholesomedev** [comment]
I don't see the need to follow semver, frankly. We will not have any public APIs for developers to use, so the concept of breaking changes does not apply to us.

But yeah, I'm not sure how to do versioning for an app. Maybe once we release the minimum viable product, we bump to 1.0.0? And from then on every deployment is a `minor` release? And then if it ever makes sense to release `2.0.0`, we can bump `major`?

**Comment by deltaidea** [comment]
We don't necessarily _have_ to follow semver, I'm just used to it. Let's close this for now.
