### ISSUE TITLE
Should we rename `lambda-assign-env` to just `assign-env`?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#402]

**Comment by forabi** [comment]
We might need a better name with the addition of the two new functions. Maybe something along the lines of `route-to-env`?

**Comment by wholesomedev** [comment]
Sounds good. Or `route-user`, `route-visitor`, `route-request`, etc...

**Comment by forabi** [comment]
Renamed to `route-request`.
