### ISSUE TITLE
Some files in config folders confuse some of the tools we use

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#413]
Having a file named `package.json` in `clownOverrides` confuses tools like ESLint and TSLint:

![screenshot from 2018-04-16 22-22-43](https://user-images.githubusercontent.com/1012761/38830373-cd96a4b6-41c4-11e8-8126-697c7d62cdb2.png)

ESLint will look for `"lodash"` in the nearest `package.json`, and this one does not have `"lodash"`, because it's intended for overriding the config values:

```json
{
  "scripts": {
    "check-ts": "run-p 'check-ts/*'",
    "pre-push": "yarn test",
    "pre-commit": "yarn pretest"
  }
}

```

I think the same applies for `.gitignore`, which would make git think we need to ignore the files listed in the override file in `./clownOverrides` (although it's less likely we would hit this issue).

**Comment by wholesomedev** [comment]
What do you think if we allow some optional prefixes: `c` and `clown`. So files can be named `c.package.json` or `clown.package.json` and when clown processes those, it would remove those prefixes?

Or can you think of another solution?

**Comment by forabi** [comment]
Maybe we can add a new field to `clown.json`, let's say `renameFiles` which is a map of files to be renamed when composing the configurations? Something like this:

```json
{
  "extensions": [
    "./node_modules/@hollowverse/config/clown/common",
    "./node_modules/@hollowverse/config/clown/typescript",
    "./node_modules/@hollowverse/config/clown/babel",
    "./node_modules/@hollowverse/config/clown/lambda",
    "./clownOverrides"
  ],
  "renameFiles": {
    "gitignore": ".gitignore",
    "packageJson.json": "package.json"
  }
}
```

**Comment by wholesomedev** [comment]
Do you think this renaming configuration is better than having a renaming
convention?

From an implementation point of view, the convention would be easier. And
from a consumer perspective it would mean a smaller clown.json file.

But it may also seem magical which can be annoying.

Another approach is to add a rename utility method to clownFs in
clownCallback.js (I’ve been thinking about how to make it possible to write
clownCallback in TS by the way, and support typing too, and I think I have
a few reasonable approaches in mind)
-- 
Sent from my iPhone

**Comment by forabi** [comment]
You're right. I like convention over configuration. Both of the approaches
you suggested sound fine.

**Comment by forabi** [comment]
By the way, I tried to make VS Code understand the type of clownFs via
JSDoc but it just couldn't find the types. It's definitely worth another
shot.

**Comment by wholesomedev** [comment]
Cool. I think `c-` can be a good "escape" prefix. So files can be escaped like `c-eslintrc.json`, `c-package.json`, and `c-.gitignore`.

With regard to allowing clownCallback to be written in TypeScript: I'm thinking of allowing `clownCallback` to be either written with a `ts` or a `js` extension. If `clownCallback` exists with a `ts` extension, it will be required with `ts-node` from within clown itself. 

And to facilitate typing, we can export the type of `clownFs` from `@hollowverse/clown` so that it can be used as such:

```ts
import {ClownFilesystem} from '@hollowverse/clown';

export default function clownCallback(clownFs: ClownFilesystem) {
// etc...
}
```

What do you think about that?
