### ISSUE TITLE
clown check does not fail if .gitignore has entries not specified in any config

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#416]
If I add:

```
.vscode/**
```

to `./.gitignore`, `yarn clown check` should fail because this line is not specified in any of the configs references in `clown.json` or any overrides.

**Comment by wholesomedev** [comment]
This is not the way clown works currently.

clown would complain if configuration is missing or if, in the case of JSON, a key has a different value from what clown expects. clown would not complain if a JSON object has more values. For example, in the case of `package.json`, not all values come from source files. Some configurations pre-exist in the destination `package.json`.

We can make clown more strict where it requires all configurations to come from a source file. 

But do you think that would be better? In that scenario, the developer would not be able to edit, say, `package.json` directly. They would have to edit `clownOverrides/package.json` and have clown write the root `package.json`. At that point, we should probably rename `clownOverrides` to `configSources` or something...

**Comment by forabi** [comment]
I should have realized that because otherwise we would not have been able to add packages to `package.json`. No I don't think we should be more strict, because it would be too inconvenient to, say, add or remove a package from `package.json`.
