### ISSUE TITLE
Real Testing™ architecture

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#42]
This issue is dependent on the [Build Real Testing™ infrastructure](https://github.com/hollowverse/hollowverse/milestone/3) milestone.

---

# The Problem

Integration and unit tests are essential to maintaining a healthy, well vetted codebase and application. On the other hand, they are costly to write and maintain. They more than double the cost of development. Until recently, there weren't good alternatives to having good test coverage for JavaScript applications. But with the rise of type-safety and machine data analysis in the JavaScript world, the situation may be changing.

# An Alternative Approach

We already use TypeScript, which eliminates big chunk of the need for unit testing. But what about integration testing? 

I'm proposing we use an approach like Canary Releases combined with logging and monitoring as a replacement for integration testing. Here's how...

## Overview

Say we have a new branch that we want to merge to master. We release this branch to a small percentage of our users and collect key metrics from user interactions to determine whether the changes are good or bad. Based on the results, we either merge the changes to master or make further changes and retest the branch.

## The architecture

The below is one way to architect such a pipeline

[![screen shot 2017-04-16 at 5 55 14 pm](https://cloud.githubusercontent.com/assets/26730388/25075668/f62c0d2e-22cd-11e7-8249-cd3f90c10cf9.png)](https://docs.google.com/drawings/d/1coCIVuGW9ZXxqbEGAn8iw7dDU0s-e3qLeFsWfSZ6Ugo/edit)

## Nodes in this diagram

Below is a description of the nodes in the diagram

### Developer

A Hollowverse developer who has the right to deploy to production

### ChatOps

A Chat bot, like [Hubot](https://hubot.github.com/), through which a developer can interact with Release Manager server

### Release Manager

A Node server that routes a small portion of traffic to the Testing Environment and the rest of the traffic to the Production Environment.

### Env

We will have two environments: Testing Environment and Production Environment.

An environment consists of: 

* Node web server, which does server-side rendering and serves static assets (HTML, CSS, JS)
* Firebase Cloud Functions
* Firebase Database

### Logging service

Logging service as discussed here https://github.com/hollowverse/hollowverse/issues/9

## How it works

You're a developer with deploy rights. Say you have an open PR for branch `feature-a`. You go to the Discord #deploy channel and tell Hubot that you want `feature-a` branch tested. Hubot in turn tells Release Manager that `feature-a` branch needs testing. If there are no branches currently under test, Release Manager will deploy `feature-a` to the Testing Environment and start routing a portion of traffic to the Testing Env. As users hit Testing Env, metrics will begin to accumulate in the logging service. Release Manager will check the logs periodically(?) to check if enough metrics(?) have been collected. Once enough metrics have been collected, Release Manager will ping Hubot who in turn will ping the developer. Based on the results of the test, the developer can decide to merge to production or make changes and re-test.

### How often is "periodically"?

In the beginning, Release Manager should check with logging services frequently to see if there are any major issues, like a significant drop in page-view counts or app crashes. In such a case, Release Manager should report back quickly. If no major issues are discovered quickly, Release Manager can check every 10 minutes or so, I guess?

### How much is "enough metrics"?

This will depend on how much traffic we have. In the beginning, when we have little traffic, "enough" will also be little. As our traffic grows, we should be able to get good amounts of data quicker.

## Wouldn't this be a slow feedback loop?

Without enough traffic, yes, this will be slow and we won't rely on it too much. But as traffic grows, we'll be able to see results quickly. We should get enough data within 10-20 minutes with enough traffic? 🤞 

## Limitation of the Testing Env and Production Env

It's possible to deploy different environments of Node web servers and static assets (HTML, CSS, JS), but I don't know if it's possible to deploy Firebase Cloud Functions to different environments. Worst case scenario, we can put Cloud Functions that are under test in a different folder (of course, not manually, but through a build step or something).

**Comment by deltaidea** [comment]
So basically use users as beta testers? Let's go for it for now, sure.

I feel a bit unsafe without tests — like in an ocean without a tether. But I don't have a strong argument for my case, so let's do it.

**Comment by wholesomedev** [comment]
@deltaidea Yeah, I totally get what you mean. Testing has always been very important to me, but it is very darn costly!

Let's see how things play out with this approach and keep reevaluating...

**Comment by forabi** [comment]
This is for future reference: https://cloud.google.com/appengine/docs/admin-api/deploying-apps

**Comment by wholesomedev** [comment]
This issue is kind of outdated now. We've discovered that we no longer need Release Manager, and we've decided not to use Cloud Functions. 

It has served its purpose by communicating the idea of using deployment versions and logging instead of unit and integration testing. That's good enough.

I'll go ahead and close it.
