### ISSUE TITLE
Does Clown recognize JSON files that do not have a .json extension?

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#422]
Some files like `.stylelintrc` and `.graphqlconfig` are regular JSON files but they do not have the `.json` extension. Can Clown merge configurations in these files?

**Comment by wholesomedev** [comment]
Yes, if the content is parsable by JSON.parse, it will be handled as JSON and possible to extend.

By the way, I think we should prefer using a config file name with an extension if possible. I know, for example, that stylelint does support .stylelintrc.json. 

graphqlconfig doesn’t however, but if the content inside the config file is a valid JSON, it’ll be extended as such.

**Comment by forabi** [comment]
> I think we should prefer using a config file name with an extension if possible.

Totally agree. I don't know where this convention of no extension came from, but it looks like developers are starting to realize it does not make much sense.
