### ISSUE TITLE
Can we support JSON5 and JSON with comments in Clown?

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#423]
`.gqlconfig` is a file used by GraphQL for VS Code (not the same as `.graphqlconfig`), and it uses [JSON5](https://github.com/json5/json5) syntax.

Other files like `tsconfig.json` support comments in JSON, which is not part of the spec, but it works for a lot of configuration files.

It would be nice if Clown could read these files and merge configurations like it does for standard JSON. This is not urgent in any way, JSON5 is a superset of JSON so we can work around the merging issue by writing standard JSON in JSON5 files.

**Comment by wholesomedev** [comment]
If there is a JSON5 library that can parse a JSON5 string to a JS object, we could just substitute it where we use JSON.parse in our code. But we would lose the comments in the merged result. Bringing the comments to the merged result may require some implementation.
