### ISSUE TITLE
We should simplify our setup (even at the cost of performance)

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#424]
This is something we talked about before, but I couldn't help but bring it up again...

I was trying to work on #339 and address some _other_ errors and warnings that I saw in console, but I was immediately blocked by our complex webpack and SSR setup. I didn't know how to proceed.

I think this complexity has brought us great benefits in terms of performance, but I feel that it also made it difficult to evolve the app.

I think our first priority should be to have an **extremely easy to maintain codebase** because otherwise **we'll get bogged down very quickly**. Unfortunately, this means sacrificing some performance. 

While we may not score the best grades on Lighthouse and WPT metrics, we can still optimize as much as we can without impacting the maintainability of our codebase. Even with having maintainability as a first priority, I think we would still be able to deliver acceptable performance to low bandwidth users.

Last time we discussed this topic on Discord, our conclusion was that if we can hide the complexity of webpack and SSR we would be able to improve developer experience and maintainability. That's a reasonable conclusion. However, after some thinking I realized that hiding the complexity of webpack and SSR is a massive undertaking in its own right. While we maybe able at some point in the future to take up this challenge, I don't think we currently have the means to do so.

At our current stage, our best bet is to build the app in the most maintainable and developer-friendly manner while eliminating areas where we could get bogged down.

The main areas of complexity that I see are SSR and our build processes.

Here's what I propose we do with them:

## SSR

I'm okay with completely disabling SSR. However, if there's a plug-and-play solution that we can drop-in and that would not impact our ability to evolve the app, we could explore it.

I don't know much about SSR, but I imagine it's not a binary thing. It's not like we can have 0% SSR or 100% SSR. So, if there's a solution where we can achieve partial SSR with no maintainability cost, we could explore that too.

Otherwise, I think we should drop SSR.

## Build process

I think our development and production build processes should be optimized for debuggability and developer-friendliness. Ideally, we should be using external resources as much as possible so that, again, we wouldn't get bogged down or held back by our build processes.

---

What do you think?

**Comment by forabi** [comment]
> However, after some thinking I realized that hiding the complexity of webpack and SSR is a massive undertaking in its own right. 

True. We want to focus on the actual development of the app, not spend our time building, configuring and setting up tools.

> However, if there's a plug-and-play solution that we can drop-in and that would not impact our ability to evolve the app, we could explore it.

> I think our development and production build processes should be optimized for debuggability and developer-friendliness.

Well, we _could_ drop SSR, and I really don't think it would hit the performance scores that much, but that may not help us get rid _completely_ of all the ad-hoc processes that we have. Plus, if we were to drop SSR, we wouldn't need Lambda anymore, we would just upload the build to S3 and serve the bucket on `hollowverse.com`.

I have come to appreciate the friendliness and ease of use of Serverless. It greatly simplifies the development and deployment processes. I think what we need here is a similar tool that can replace the ad-hoc scripts and configurations that we have built and abstract them in a developer-friendly package.

I think [Next.js](https://github.com/zeit/next.js/) is the perfect tool for `hollowverse/hollowverse`. When we started, it was not very mature and it was more opinionated on what technologies it supported. It didn't support TypeScript or Sass, but it is now pluggable and can expose the underlying Webpack configuration so we can customize things a little bit. It supports SSR, server-side data fetching, HMR and route-based code-splitting out of the box. So if it can really help improve our DX and build process, I don't see any need to compromise on performance.

What do you think?

**Comment by forabi** [comment]
If you don't think Next.js will help, I'm totally okay with dropping SSR and switching to a client-side SPA hosted on S3 (might be a good chance to drop Webpack and explore Parcel as well :smiley:)

**Comment by forabi** [comment]
> I don't know much about SSR, but I imagine it's not a binary thing. It's not like we can have 0% SSR or 100% SSR.

Actually it is a binary thing from the dev setup point of view. You either write a simple Webpack config that serves `index.html` or you compile 2 versions of the app: one that works in Node.js to serve dynamic SSR HTML markup and the other works in the browser. So supporting 1% SSR is as complex as supporting 100% SSR in that sense.

**Comment by forabi** [comment]
> I was trying to work on #339 and address some other errors and warnings that I saw in console, but I was immediately blocked by our complex webpack and SSR setup. I didn't know how to proceed.

Could you tell me exactly what issues you had? I know our set up is not perfect but usually all I have to do to start working is running `yarn dev`. Of course, if I'm working on webpack config itself, I always need to stop the command and re-run it every time I change something in Webpack config files. That applies to both SSR and no SSR setups.

**Comment by wholesomedev** [comment]
As discussed on Discord, we think the best approach now is to drop SSR completely.

When we do that, we'll see:

* How our setup looks like without SSR
* How our SEO is impacted without SSR

And from there we would have a benchmark of the cost/benefit of SSR.

We will continue to use Lambda to serve our non-SSR web app. And we'll continue to use webpack, upgrading to webpack 4 when possible.

**Comment by wholesomedev** [comment]
>> I was trying to work on #339 and address some other errors and warnings that I saw in console, but I was immediately blocked by our complex webpack and SSR setup. I didn't know how to proceed.
>
>Could you tell me exactly what issues you had? I know our set up is not perfect but usually all I have to do to start working is running `yarn dev`. Of course, if I'm working on webpack config itself, I always need to stop the command and re-run it every time I change something in Webpack config files. That applies to both SSR and no SSR setups.

I was mostly playing with the code a little, seeing what warnings/error messages show up in console, and trying to fix those. There were warnings about babel plugin css chunks, something about matching divs, an error from hot module reloading, and a couple of others.

**Comment by forabi** [comment]
> There were warnings about babel plugin css chunks, something about matching divs, an error from hot module reloading, and a couple of others.

:smiley:

To be fair, HMR is really hacky and has never worked reliably for me, regardless of how I set up Webpack.

**Comment by wholesomedev** [comment]
I've created #427 to track the result of this discussion. Will close out this one.
