### ISSUE TITLE
NP page is not scrolled to the top when it first loads

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#428]
Steps to reproduce:

* Go to https://dev.hollowverse.com/Ray_J on Safari iOS

Expected behavior: NP image is not covered by the page's nav bar

Actual behavior: NP image is partly covered by the page's nav bar. Scrolling a little bit to the top is needed to view the full image.

Does not affect Chrome on Android.

**Comment by wholesomedev** [comment]
Apple engineers seem to have failed in making Safari work well with a sticky navbar at the top. Since we have to support this broken browser, I'm wondering if we can change the way we've implemented the top navbar.

For example: we give the navbar position static (default positioning), and only when it has completely scrolled out of view, we change its positioning to fixed and animate it down. 

It's really not an ideal experience, but we have to do something about this, and I can't think of another solution.

**Comment by forabi** [comment]
> It's really not an ideal experience, but we have to do something about this, and I can't think of another solution.

While also not ideal, the workaround in #431 maintains the current experience which I think is better.

**Comment by forabi** [comment]
> While also not ideal, the workaround in #431 maintains the current experience which I think is better.

I reverted this, but not completely. The issue in the title is now fixed (probably, it seems that one cannot be sure of anything with Safari) but there is another issue where the `NotablePersonBody` jumps below the NavBar when it is in the loading state.

**Comment by forabi** [comment]
> another issue where the NotablePersonBody jumps below the NavBar when it is in the loading state.

This one seems to be reproducible on Chrome for Android as well.

**Comment by wholesomedev** [comment]
@forabi I'm unable to reproduce this, could you provide instructions on how to reproduce?

**Comment by forabi** [comment]
Here's the demo of the issue I'm talking about: https://www.dropbox.com/s/r9c0xj8a9b3jps0/Bug%20demo.mp4?dl=0

Notice that for a brief moment the NP image placeholder is touching the navbar. It seems as if some margin/padding is missing between the two. For some reason I wasn't able to reproduce on Safari.

As for the issue in the title, Safari seems to be inconsistent in its buggy behavior. Sometimes I open the page and see the page half scrolled, I close the tab and open the exact same page and it's not scrolled. I don't know what is happening here, it could be that we are using an intersection observer polyfill for Safari which uses scroll events and Safari may be throttling those events?

> For example: we give the navbar position static (default positioning), and only when it has completely scrolled out of view, we change its positioning to fixed and animate it down.

I'll give that a try and see if it fixes the issue.

**Comment by forabi** [comment]
Please feel free to test the changes in #441 on https://hollowverse.com/Tom_Hanks?branch=internal

In my tests, the scrolling issue is not fixed. I'm not sure how to proceed here. I no longer think the scrolling issue has anything to do with fixed/sticky positioned elements, and it may need further debugging.

**Comment by wholesomedev** [comment]
I think this is fixed in #442. I'm going to go ahead and close it! 🎉
