### ISSUE TITLE
Could strict linting rules be off-putting to potential contributors?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#446]
I'm just wondering if having many linting rules could be off-putting to contributors.

For stylistic choices, I mostly agree with [Nicholas Zakas](https://twitter.com/slicknet/status/917841663375974400) (creator of ESLint):

> IMHO If some part of your JavaScript code style can't be automatically applied using ESLint --fix or Prettier, then it's not important.

However, it can be argued that so-called stylistic choices have practical implications.

What do you think?

**Comment by forabi** [comment]
I agree. We should probably remove airbnb config and only pick rules that can prevent potential bugs.

**Comment by wholesomedev** [comment]
Cool, I'll repurpose this issue then
