### ISSUE TITLE
Relax linting rules

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#448]
After the discussion in #446, we think we should relax linting rules

**Comment by forabi** [comment]
Just looking at [all the rules](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/) in airbnb config I realized there's a lot of effort put into making that guide and there's just too many useful rules. I no longer think we should disable this config. Instead, we should just disable stylistic rules that don't help with the correctness of the code. I think we should disable these rules as they pop up while working on the codebase.
