### ISSUE TITLE
Migrate secrets to AWS Secrets Manager

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#451]
We cannot currently expose our AWS architecture unless we migrate secrets to AWS Secrets Manager. Secrets stored in AWS Secrets Manager are accessed at runtime and can be restricted by IAM roles/users.

* [x] `hollowverse/hollowverse` (#464)
* [x] `hollowverse/api` (https://github.com/hollowverse/api/pull/89)
* [x] `hollowverse/process-image` (https://github.com/hollowverse/process-image/pull/12)
* [x] `hollowverse/track-performance` (https://github.com/hollowverse/track-performance/pull/43)

**Comment by wholesomedev** [comment]
Should we upgrade this to a feature blocker? I feel this is important for documentation?

**Comment by forabi** [comment]
> Should we upgrade this to a feature blocker?

:+1:
