### ISSUE TITLE
Clown does not copy files in clown/typescript/src

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#458]
In `@hollowverse/config` we have [a deep configuration file for ESLint](https://github.com/hollowverse/config/tree/master/clown/typescript) which is expected to be copied to or merged with `<cwd>/src/.eslintrc.json`. ~It looks like Clown is not considering files located one or more levels deep in the extension folder. It might be because of the [glob pattern we are using](https://github.com/hollowverse/clown/blob/fc87c4fc1736052be25c2d090d2892f8569d2371/src/computeFileContents.ts#L53).~

**Comment by wholesomedev** [comment]
@forabi This is interesting. The files inside `.vscode` get copied correctly but the files inside `src` don't? Both groups of files have the same depth.

**Comment by forabi** [comment]
See [my comment](https://github.com/hollowverse/clown/pull/15#issuecomment-388169425):

> Never mind, it turns out this is not an bug in Clown. This is again a problem with the published package. `src` is ignored in `.npmignore`.

**Comment by forabi** [comment]
I've updated the issue title and labels.
