### ISSUE TITLE
Add help document

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#468]
I'm thinking of creating a help.md file, putting it inside `.github` folder in h/hollowverse and linking to it from various different places.

help.md would contain instructions for a person to get help with anything Hollowverse related. It would invite them to file an issue, email us, or join us on Discord.

Does that make sense?

**Comment by forabi** [comment]
Yeah, I don't see why not :smile:. Will this file be surfaced somewhere by GitHub or will we need to link to it from `README.md`?

**Comment by wholesomedev** [comment]
@forabi I don't think help.md will get any special treatment by being inside .github, so maybe I should not put it there...I just don't wanna put it at the root either. Maybe I'll make a wiki page instead of a help.md file.

**Comment by forabi** [comment]
@wholesomedev Can we close this now?

**Comment by wholesomedev** [comment]
👍
