### ISSUE TITLE
Pipe AWS logs to Splunk

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#472]
I'm trying to create a [Splunk dashboard](https://prd-p-kwnk36xd58jf.cloud.splunk.com/en-US/app/search/real_time_metrics?form.field1.earliest=-24h%40h&form.field1.latest=now) that will give us insight into the health of our system at a glance.

So far I only have the following metrics in it:

* Runtime client-side errors
* Successful page loads
* Unique session IDs

Each one split by master/beta.

Obviously, there's a lot that's happening in AWS, which is not visible in Splunk. I think it would be better if we pipe all of our logs to Splunk so we have a central place for analytics. There's a good amount of information online on how to stream AWS logs to Splunk.

**Comment by forabi** [comment]
I'm unable to see any data. Is this a permission issue?

> Error in 'SearchParser': The search specifies a macro 'assign_env' that cannot be found. Reasons include: the macro name is misspelled, you do not have "read" permission for the macro, or the macro has not been shared with this application. Click Settings, Advanced search, Search Macros to view macro information. 

![screenshot from 2018-05-14 22-44-24](https://user-images.githubusercontent.com/1012761/40019662-8a6c216a-57c8-11e8-956e-8cc74b86e09b.png)

**Comment by wholesomedev** [comment]
@forabi I've updated the permissions. Try again?

**Comment by forabi** [comment]
@wholesomedev It works now! :+1:

**Comment by forabi** [comment]
I've added a new panel, "Failed page loads"
