### ISSUE TITLE
Move more pages to the new Hollowverse

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#474]
According to our [Google Analytics dashboard](https://datastudio.google.com/u/0/reporting/1sg9ER2pF74eQv0GOLjPLYA5xbSc24eiG/page/1M), we have around 7,000 daily users on the legacy Hollowverse and around 200 daily users on the new Hollowverse. 

I think we're ready to go above 1,000 daily users on the new Hollowverse.

Can we move more of our bottom-most pages from the legacy Hollowverse to the new Hollowverse to get to 1,000+ on it?

**Comment by wholesomedev** [comment]
Will the changes in #475 really get us to 1,000+ users daily? According to our analytics, the numbers are still pretty low, even today?

**Comment by forabi** [comment]
@wholesomedev #480 should address this.

**Comment by forabi** [comment]
@wholesomedev I'm going to re-open this and keep tweaking redirected pages until we get to 1,000 unique users

**Comment by wholesomedev** [comment]
[Yesterday](https://datastudio.google.com/u/0/reporting/1sg9ER2pF74eQv0GOLjPLYA5xbSc24eiG/page/1M) we had about 850 uniques on the new Hollowverse. Yesterday had particularly high traffic compared to our usual numbers though, so I think we need to move more pages to get to 1,000+.

**Comment by forabi** [comment]
@wholesomedev we hit +1,000 users for the first time

![screenshot from 2018-05-21 20-47-13](https://user-images.githubusercontent.com/1012761/40321597-3c7af182-5d38-11e8-8316-25a2f50d94a4.png)

**Comment by wholesomedev** [comment]
Awesome, I think we can close this issue now!
