### ISSUE TITLE
Parse AWS logs in Splunk correctly

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#478]
The AWS Splunk logs don't seem to be usable in their current state because they are not being parsed correctly.

[This page](https://www.splunk.com/blog/2017/02/03/how-to-easily-stream-aws-cloudwatch-logs-to-splunk.html) shows some information on how to parse AWS logs correctly.

I also saw under Splunk Apps and Add-Ons there are AWS related apps and add-ons 
![image](https://user-images.githubusercontent.com/26730388/40094622-eea16dd4-587c-11e8-87ef-de02f9770ad8.png)

I wonder if we can leverage those to get more helpful dashboards?

**Comment by forabi** [comment]
@wholesomedev Getting somewhere with the Splunk add-on and app for AWS, the numbers are starting to show up :smile: 

![image](https://user-images.githubusercontent.com/1012761/40448242-a59a0eea-5edd-11e8-8339-9d9250fd9e87.png)

![image](https://user-images.githubusercontent.com/1012761/40448374-04d0874a-5ede-11e8-9080-8e017b7310ca.png)

**Comment by forabi** [comment]
I enabled all relevant types of inputs in the AWS app. We know stream all AWS logs to Splunk with the exception of AWS Config (which I looked at, and it does not seem like something we need for now).

![image](https://user-images.githubusercontent.com/1012761/40452698-6f487daa-5eeb-11e8-840d-c703725dde01.png)

**Comment by wholesomedev** [comment]
@forabi I don't see all the ones you've created. For example, I don't see `CloudWatchLogsForProcessImage`. I wonder if that's a permissions issue?

**Comment by wholesomedev** [comment]
By the time I checked Splunk logs, there were over 170,000+ events. But most of them are for `s3://hollowverse-cloudfront-access-logs`. When I excluded `s3://hollowverse-cloudfront-access-logs` by doing

```
host="prd-p-kwnk36xd58jf" NOT source="s3://hollowverse-cloudfront-access-logs*"
```

I only got 800 events back. If we don't have an immediate pressing need to stream `s3://hollowverse-cloudfront-access-logs`, should we not pipe them to Splunk? They might be slowing down our instance and searches?

**Comment by forabi** [comment]
> If we don't have an immediate pressing need to stream s3://hollowverse-cloudfront-access-logs, 

Ah, the S3 bucket name was a mistake. I basically re-used a bucket we already had to save all the logs into. Not just CloudFront access logs. So when you search with that source, you are basically searching in everything:

![image](https://user-images.githubusercontent.com/1012761/40500987-40d9f88c-5f8f-11e8-8830-1f921bcf0524.png)

Unfortunately, the S3 bucket cannot be renamed, I'll need to create a new one and change the log destinations.

By the way, I don't think you will need to do manual searches, just visit 
https://prd-p-kwnk36xd58jf.cloud.splunk.com/en-US/app/splunk_app_aws/

Use the links at the top navigation bar to view insights on almost everything in our AWS account.

**Comment by forabi** [comment]
> I don't see all the ones you've created. For example, I don't see CloudWatchLogsForProcessImage. I wonder if that's a permissions issue?

Let me check the permissions

**Comment by forabi** [comment]
With regard to the actual CloudFront access logs, I enabled them so that we could get traffic analysis and information about cache hits/misses:

![image](https://user-images.githubusercontent.com/1012761/40501492-b1cd6f50-5f90-11e8-9132-fe29dd0ed513.png)

Most of these are already available in the AWS CloudFront console, but it's nice to have everything in Splunk. I don't mind removing them though.

**Comment by forabi** [comment]
and with regard to the permissions, I don't see any UI option to set or change permissions on inputs. Are you looking at inputs on https://prd-p-kwnk36xd58jf.cloud.splunk.com/en-US/app/Splunk_TA_aws/inputs? Those do not have a visible UI link as far as I can tell.

**Comment by forabi** [comment]
> Unfortunately, the S3 bucket cannot be renamed, I'll need to create a new one and change the log destinations.

Done. The new logs will be streamed to a new bucket named `hollowverse-logs`.

**Comment by wholesomedev** [comment]
>and with regard to the permissions, I don't see any UI option to set or change permissions on inputs. Are you looking at inputs on https://prd-p-kwnk36xd58jf.cloud.splunk.com/en-US/app/Splunk_TA_aws/inputs? Those do not have a visible UI link as far as I can tell.

Yes, I see them there 👍

> it's nice to have everything in Splunk

Yes, I agree. I just wasn't sure they were useful. I guess they are.

**Comment by forabi** [comment]
So this issue is complete I guess? Should we close it?

**Comment by wholesomedev** [comment]
Yes, I think so. We can open more tickets if we run into any issues in the future...
