### ISSUE TITLE
Should we log track-performance results to Splunk?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#479]
I feel it makes more sense to log track-performance results to Splunk rather than sending a PR to GitHub.

Now that we have reports for several different URLs, parsing the results mentally by scanning the PR message that hollowbot makes is kind of hard.

One benefit of the PR method is the diff which shows a comparison between the old and the new number. But we can get the same benefit in Splunk by making a chart that shows the movement of the performance indicators over time.

What do you think?

**Comment by forabi** [comment]
> parsing the results mentally by scanning the PR message that hollowbot makes is kind of hard.

Yes, that's my experience too.

I think moving this data to Splunk makes a lot of sense. We would be able to visualize the performance changes over time and maybe co-relate them with some of the changes in other log sources.
