### ISSUE TITLE
Related people images are too big on desktop when only 3 are listed

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#493]
See https://hollowverse.com/Prince_Harry

![screenshot from 2018-05-20 20-16-49](https://user-images.githubusercontent.com/1012761/40281706-9140c71c-5c6d-11e8-83a8-65ebc1ea8abe.png)

**Comment by wholesomedev** [comment]
Hmmm, on mobile, it looks ok. On desktop it's a little disproportionate.

Perhaps we can set a max-width on these images and center-justify the content of "Other interesting profiles" to handle this edge case?
