### ISSUE TITLE
Investigate the possibility of using Primsa for the API

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#497]
[Prisma](https://www.prismagraphql.com) looks very promising and I think we should take a closer look at it and see if it can replace our custom GraphQL layer. If it's a good fit for our use case, we could greatly reduce the API development time.

**Comment by forabi** [comment]
Here are my findings so far:

* Large parts of Prisma are written in Scala and are expected to run in Docker. We cannot run Docker on Lambda so we will need to host the server on Elastic Beanstalk.
* Prisma _does not_ replace our GraphQL resolvers. It creates a GraphQL API to access the database. So there will be two GraphQL APIs:

  * The database GraphQL API created by Prisma. Tables in the database are created by Prisma based on the database GraphQL schema. What does that mean? It means Prisma is a way to define the database tables using GraphQL syntax:

    ```graphql
    type User {
       id @unique
       role @default("contributor")
    }
    ```

    Prisma will take that schema and map each type to a table, magically setting up relationships between the tables and handling updates to the database schema automatically.

  * The public-facing GraphQL API which we write. 

    [Why do we need another API on top of the database API?](https://www.prisma.io/docs/tutorials/build-graphql-servers/development/build-a-graphql-server-with-prisma-ohdaiyoo6c#why-not-use-the-prisma-api-directly-from-your-client-applications)

    > Prisma turns your database into a GraphQL API, exposing powerful CRUD operations to read and modify the data. This means letting your clients talk to Prisma directly is equivalent to directly exposing your entire database to your clients.

    This is where we write our resolvers which use the Prisma SDK to access the database in a type-safe manner. Prisma SDK is automatically-generated, strongly-typed code that allows access to the underlying database API like an ORM:

    ```ts

    const resolvers = {
      Query: {
        posts: (
          _,
          { where, orderBy, skip, after, before, first, last },
          ctx,
          info
        ) => {
          // db.query.posts is part of the auto-generated Prisma SDK
          return ctx.db.query.posts(
            { where, orderBy, skip, after, before, first, last },
            info
          );
        }
      },

      Mutation: {
        createPost: (_, { data }, ctx, info) => {
          return ctx.db.mutation.createPost({ data }, info);
        },

        deletePost: (_, { id }, ctx, info) => {
          return ctx.db.mutation.deletePost({ where: { id } }, `{ id }`);
        }
      }
    };
    ```


So the way I see it is that Prisma is a glorified type-safe ORM which allows defining database schema with GraphQL syntax and handles database migrations. This is cool actually and it may work better than TypeORM. It may introduce some complexity in deployment and development though. That's something I still need to check.

**Comment by wholesomedev** [comment]
>Large parts of Prisma are written in Scala and are expected to run in Docker. We cannot run Docker on Lambda so we will need to host the server on Elastic Beanstalk.

This doesn't sound good. Other than our database, we have a consistently serverless architecture in which Primsa wouldn't fit naturally. 

Would Primsa buy us enough development productivity to justify complicating our architecture? 

>Prisma is a way to define the database tables using GraphQL syntax

It seems to me that Primsa is yet another layer that developers would need to be aware of and understand (on top of GraphQL and MySQL).

I feel that at this point in time, this is something to be avoided. In the future, it might be worth looking into this or a similar solution again.

However, as you know, I'm not very familiar with our backend and API, so my opinion here might not make complete sense. Let me know if you are seeing things differently.

**Comment by forabi** [comment]
I share your opinion mostly, however, I'd like to continue investigating this a little bit further.

Things to consider:

* Extra layer of complexity, learning curve. Is this a good trade-off?
* What about performance? Two layers of GraphQL.
* Would we be able to get rid of some of our resolvers? How much code can we remove?
* Aren't magic migrations of production databases a dangerous thing? If Prisma gets this right, it would be fantastic, but if it does not, it would be really bad.
* Are we creating a vendor lock-in? Is Prisma going to be maintained 2 years from now?

I'm leaning more towards not using Prisma. It looks like the cons outweigh the pros.

**Comment by wholesomedev** [comment]
@forabi Yeah, these also seem like important points that we would need to understand 👍

**Comment by forabi** [comment]
Based on the previous discussions, I don't think Prisma is a good choice for us. However, I wanted to see if we could make use of [`graphql-binding`](https://oss.prisma.io/content/graphql-binding/01-Overview.html) to generate a TypeScript SDK for our API.

![screenshot from 2018-06-12 22-54-56](https://user-images.githubusercontent.com/1012761/41313940-ef9db90e-6e93-11e8-84b8-e908022d7ad3.png)

While I was able to generate the SDK, unfortunately, we cannot customize which parts of the query are going to be sent (we have to write the full query). This nullifies the performance benefits of GraphQL which depend on the fact that the client can do partial queries to only get the fields that it is interested in.

It seems that `graphql-binding` is designed primarily for server-side queries and Prisma.

**Comment by wholesomedev** [comment]
👍
