### ISSUE TITLE
Use Storybook to show designs in hollowverse/design

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#498]
Lack of ability to quickly view the different states of components and the rendering of components in different viewports causes unnecessary back-and-forth communication.

We can use [Storybook](https://github.com/storybooks/storybook) to show the different states of our components and to quickly view the behavior of the components in different viewport sizes.

While Storybook is usually used to showcase small components, like `<Button />`, it works just as well for showcasing a full `<App />`. So we can have:

- Homepage
- Menu (where we show the menu states within `<App />`)
  - Logged in
  - Logged out
- Notable Person page
  - Missing NP image
  - Error
- ...etc

Using Storybook in this way would require some implementation changes in `hollowverse/design`. We will need to:

1. Remove React Router
1. Lift all state up and outside of the app itself so that all of the app states can be controlled via props
1. Figure out how to load CSS properly within Storybook

We should also deploy the result to GitHub Pages

**Comment by forabi** [comment]
Cool! I've used Storybook before and it makes a lot of sense to use it for `hollowverse/design`.
