### ISSUE TITLE
How should we decide on an error threshold?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#508]
I'm wondering if we can come up with a formula for calculating an acceptable error threshold. For example, with `PAGE_LOAD_FAILED`, we can say as long `PAGE_LOAD_FAILED` is lower than X% of total page views, we can tolerate it.

But what about run-time errors? Can we come up with a similar formula for that? The problem with run-time errors is that it's hard to tell what their impact is just by looking at the logs. One run-time error may prevent a button from working, another error could freeze the whole app, and another error may not have any user-perceptible impact.

Looking at our logs, it seems to me that it might be possible to shoot for for 0% tolerance level for run-time errors.

Alternatively, maybe we can define our tolerance for runtime errors based on a formula such as "total number of errors"/"total number of unique users". It's not a very meaningful formula, but it's the most meaningful one I could think of given the variability of runtime errors.

What are your thoughts on the tolerance levels we should shoot for for failed page views and runtime errors?

**Comment by forabi** [comment]
> The problem with run-time errors is that it's hard to tell what their impact is just by looking at the logs.

This :100:. Just looking at the different errors I see too many with the message `[object Object]` on Chrome 66. I'm using Chrome 66 but I don't get that error. There are just too many variables in play. Maybe some users are using an extension which is throwing an error? We would not be able to know.

> Looking at our logs, it seems to me that it might be possible to shoot for for 0% tolerance level for run-time errors.

Interesting. I'd say it would be pretty hard to get to 0%. But I don't think ~9% (which is what we are currently at) is acceptable either. Something between 3-5% might be more realistic.

I think we need to start parsing stack traces to inform the decision here, although it seems that some of the errors that are logged do not have stack traces unfortunately. They could be non-`Error` objects being thrown.

With regard to `PAGE_LOAD_FAILED` events, these are mostly network errors according to the logs. We currently have around 2% of pages failing to load. That's OK I guess but I'd like to see it decreasing if possible. We currently show a Retry button so even if some page fails to load due to network errors, users might still be viewing it after reload. Maybe we could track `PAGE_LOAD_FAILED` vs `PAGE_LOAD_SUCCEEDED` for the same page in the same session to confirm that?

**Comment by wholesomedev** [comment]
>Interesting. I'd say it would be pretty hard to get to 0%. But I don't think ~9% (which is what we are currently at) is acceptable either. Something between 3-5% might be more realistic.
>
>I think we need to start parsing stack traces to inform the decision here, although it seems that some of the errors that are logged do not have stack traces unfortunately. They could be non-`Error` objects being thrown.

When we see an unhandled error that doesn't have a stack trace, can we at that point throw an Error to generate a stack trace and log that?

The reason I think we shouldn't have a tolerance threshold for runtime errors is because a tolerance threshold would rely on quantity without regard for the nature of the errors.

Another alternative approach that's similar to 0% tolerance could be 0% tolerance of _unknown errors_. What I mean is that we can profile incoming errors and decide whether to act on them or not. Once we've profiled and triaged an error, it becomes a _known error_. We filter known errors out of our errors report and work toward having 0% unknown errors.

The tricky part here to me is _how do we profile and filter out an error from our error reports?_

I was hoping we wouldn't have to use a service like LogRocket or Sentry. Though, in my experience these service make debugging errors a lot easier. Do you think we should use them?

>Maybe we could track `PAGE_LOAD_FAILED` vs `PAGE_LOAD_SUCCEEDED` for the same page in the same session to confirm that?

That's a good point. When I checked yesterday, users who encountered `PAGE_LOAD_FAILED` in the Notable Person page were never able to get a `PAGE_LOAD_SUCCEEDED` on the Notable Person page. One poor soul kept going back to the search page and tried different searches and got 12 `PAGE_LOAD_FAILED` in total and wasn't able to view any Notable Person pages 🙈

**Comment by forabi** [comment]
> That's a good point. When I checked yesterday, users who encountered PAGE_LOAD_FAILED in the Notable Person page were never able to get a PAGE_LOAD_SUCCEEDED on the Notable Person page. One poor soul kept going back to the search page and tried different searches and got 12 PAGE_LOAD_FAILED in total and wasn't able to view any Notable Person pages 🙈

That poor soul was me. I was blocking requests to the API using Chrome DevTools to test something. 😂

I'll reply to the other points later today but I just couldn't resist replying to this.

**Comment by wholesomedev** [comment]
😂

**Comment by forabi** [comment]
> When we see an unhandled error that doesn't have a stack trace, can we at that point throw an Error to generate a stack trace and log that?

I don't think that will work, because most likely by the time the synthetic error is thrown, the call stack will have been cleared. I'll give it a try anyway.

> The reason I think we shouldn't have a tolerance threshold for runtime errors is because a tolerance threshold would rely on quantity without regard for the nature of the errors.

I completely agree on the quantity vs nature point.

> The tricky part here to me is how do we profile and filter out an error from our error reports?

Does Splunk support storing lists of things that could be re-used and updated? This sounds like a macro. We could use one to keep a list of "known errors" and update it regularly.

> I was hoping we wouldn't have to use a service like LogRocket or Sentry. Though, in my experience these service make debugging errors a lot easier. Do you think we should use them?

I suggested using these services before we had our logging infrastructure. I don't mind using one of these two services (or similar) but if the macro solution works fine then I don't see an immediate need to integrate a new error tracking service. If macros would be clunky or inconvenient to use for filtering out errors, we should probably give LogRocket a try.

**Comment by forabi** [comment]
By the way, I'm pretty confident that the top unhandled error message, `[object Object]` is due to this:

Chrome:
![screenshot from 2018-05-31 00-46-04](https://user-images.githubusercontent.com/1012761/40749273-1b05e7b0-646c-11e8-9e2b-496797a90a4b.png)

Firefox:
![screenshot from 2018-05-30 22-32-28](https://user-images.githubusercontent.com/1012761/40749275-1d9fa15a-646c-11e8-9d70-a2de5e090fff.png)

It should be easy to fix.

**Comment by wholesomedev** [comment]
>Does Splunk support storing lists of things that could be re-used and updated? This sounds like a macro. We could use one to keep a list of "known errors" and update it regularly.

Might also be doable by creating two searches and filtering out their intersection? Not sure, really!

**Comment by wholesomedev** [comment]
By the way, the good folks at Sentry open source a lot of their work. They have an open source browser client called Raven.js that is designed to collect breadcrumbs of errors before reporting them. I wonder if we can use Raven to report errors to Splunk?

https://github.com/getsentry/raven-js

**Comment by forabi** [comment]
> By the way, the good folks at Sentry open source a lot of their work. They have an open source browser client called Raven.js that is designed to collect breadcrumbs of errors before reporting them. I wonder if we can use Raven to report errors to Splunk?

The description at the top of `raven-js` GitHub page says: "Official Sentry SDK for JavaScript" so it looks like it's primarily designed to work with Sentry. I also took a look at [their code](https://github.com/getsentry/raven-js/blob/master/src/loader.js) and it looks very similar to what we currently have. Basically attaching event handlers for `error` and `unhandledrejection` events.

Speaking of unhandled rejections, it's really strange that we are getting this cancelation error:

Chrome:
![screenshot from 2018-05-31 00-46-04](https://user-images.githubusercontent.com/1012761/40749273-1b05e7b0-646c-11e8-9e2b-496797a90a4b.png)

We already have an `unhandledrejection` handler to handle these so I'm not sure what's going on. Somehow the rejections are not being caught by the handler. I suspect that the `Promise` polyfill provided by `core-js` or some other dependency is messing up with the native `Promise` implementation. I can only re-produce this error when navigating back and forth between the search and NP pages. It looks like it's some dynamically-loaded dependency that's causing this issue.

**Comment by forabi** [comment]
> By the way, the good folks at Sentry open source a lot of their work. They have an open source browser client called Raven.js that is designed to collect breadcrumbs of errors before reporting them. I wonder if we can use Raven to report errors to Splunk?

The description at the top of `raven-js` GitHub page says: "Official Sentry SDK for JavaScript" so it looks like it's primarily designed to work with Sentry. I also took a look at [their code](https://github.com/getsentry/raven-js/blob/master/src/loader.js) and it looks very similar to what we currently have. Basically attaching event handlers for `error` and `unhandledrejection` events.

Speaking of unhandled rejections, it's really strange that we are getting this cancelation error:

Chrome:
![screenshot from 2018-05-31 00-46-04](https://user-images.githubusercontent.com/1012761/40749273-1b05e7b0-646c-11e8-9e2b-496797a90a4b.png)

We already have an `unhandledrejection` handler to handle these so I'm not sure what's going on. Somehow the rejections are not being caught by the handler. I suspect that the `Promise` polyfill provided by `core-js` or some other dependency is messing up with the native `Promise` implementation. I can only re-produce this error when navigating back and forth between the search and NP pages. It looks like some dynamically-loaded dependency that's causing this issue.

**Comment by forabi** [comment]
With #519, the error rates are now down to around 5%. I thought that fix would reduce the rate even more, but regardless, I looked at the stats and it seems that 75% of these errors are `SyntaxError` on Safari Mobile 9.0, Chrome 45, or older Android browsers which we don't currently support.

In light of these stats, what do you think we should do? Should we support these browsers, or just accept these errors?

**Comment by wholesomedev** [comment]
@forabi I think we should filter out errors in browsers we don't support. But my concern with errors in Chrome 41 and above is SEO.

What do you think?

**Comment by forabi** [comment]
Sorry, I was not clear. The error on Chrome 45 is `Uncaught TypeError: Cannot read property 'end' of undefined ` and it's only happening for one session. It could be an extension or something, as the `source` prop on the error is empty (no source file to parse the source map).

**Comment by wholesomedev** [comment]
@forabi I think we're good then. I guess the next action item here is to find out how to create an error report within Splunk that can filter out ignored errors?

**Comment by forabi** [comment]
@wholesomedev Yes. I'm gonna look into this today.

**Comment by forabi** [comment]
> I guess the next action item here is to find out how to create an error report within Splunk that can filter out ignored errors?

The first idea that comes to my mind is to start with ignoring all errors from unsupported browsers. We could do that in the log endpoint code. We add a new property to each log event, let's call it `isBrowserSupported`, and we simply filter events that has `isBrowserSupported === false`. Doing this in the log endpoint code is easier and we should be able to re-use the `browserslist` filed in `package.json` for this.

**Comment by wholesomedev** [comment]
>The first idea that comes to my mind is to start with ignoring all errors from unsupported browsers. We could do that in the log endpoint code.

I feel this might not be too sustainable. We'll probably eventually need to figure out a way to do this within Splunk. If that happens, we'll have some filtering on the log endpoint side and some filtering on Splunk side, which is not ideal.

Another issue, although this one is of less importance, is that we would lose what we don't log completely, whereas if we log everything but filter within Splunk itself, the logs would still be there if needed for whatever reason.

**Comment by forabi** [comment]
I didn't mean we would filter events on the log endpoint side. I meant we could add this property to make it easier to filter errors _in Splunk_ because we would not have to maintain two lists of supported browsers (one in code and one in Splunk).

**Comment by forabi** [comment]
My bad, the phrasing in my comment was confusing.

**Comment by wholesomedev** [comment]
Ah, got it. Yes, that would be a good approach I think 👍

**Comment by forabi** [comment]
I've updated the dashboard to only count runtime errors on supported browsers. Let's see how the error rates will change to decide what to do next.

**Comment by wholesomedev** [comment]
If we're going to go with the 0% unknown error tolerance approach, there aren't any more action items in this issue. Should we close?

**Comment by forabi** [comment]
Yeah, I guess so!
