### ISSUE TITLE
New pages not being indexed properly by Google

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#512]
I was checking our [Google Analytics dashboard](https://datastudio.google.com/u/0/reporting/1sg9ER2pF74eQv0GOLjPLYA5xbSc24eiG/page/1M) to see the number and I noticed that the New Hollowverse "Users" numbers dropped somewhat suspiciously. That could be because of fluctuation in the interest in the NPs who were migrated to the New Hollowverse, or it could be something else...

I thought it might also be that Google is lowering the ranking of the new pages because it can't see their content. So I used the [Fetch as Google](https://support.google.com/webmasters/answer/6066468?hl=en) tool to check how Google sees [Tom Hanks](https://hollowverse.com/Tom_Hanks) page. Unfortunately, I found out that Google only sees a blank gray page without any content!

I did a little bit of research into the matter and found [this article](https://medium.com/@gajus/react-application-seen-as-a-blank-page-via-fetch-as-google-afb11dff8562) which seems to be helpful. And I also saw this [relevant video](https://www.youtube.com/watch?v=JlP5rBynK3E) by a Google Search engineer about how to optimize SPAs for search engines.

My guess here is that we might need to transpile and perhaps polyfill more aggressively because the Googlebot can't execute our JavaScript. Not sure though.

**Comment by forabi** [comment]
Searching on Google for some NPs shows results with no metadata too. As far as I know, Googlebot uses Chrome 41 to render pages, which means the page should work fine considering we are transpiring to ES5 🤔. I'll dig deeper into this.

**Comment by forabi** [comment]
I downloaded [Chromium 41](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/310958/) and spinned up a Windows 7 VM. I got a blank page on hollowverse.com/Tom_Hanks. DevTools showed the following stack trace:

![screenshot from 2018-05-30 07-57-47](https://user-images.githubusercontent.com/1012761/40699821-476511ec-63df-11e8-9040-416e2aa5a9e1.png)

Following the first stack frame leads to this line of code:

![screenshot from 2018-05-30 07-58-12](https://user-images.githubusercontent.com/1012761/40699831-51ca3bda-63df-11e8-9501-fcf8de6291ef.png)

**Comment by forabi** [comment]
Looks like `Object.assign` is not supported in Chrome 41.

**Comment by forabi** [comment]
I think I've figured it out: although we are transpiling the language syntax to ES5, we are not including the polyfills for language features. `babel-preset-env` did that automatically, but we switched to `preset-2015`.

**Comment by forabi** [comment]
Trying a fix on an internal branch.
