### ISSUE TITLE
We should have an automated way to detect issues like #512

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#514]
For JS errors that block rendering of the page, the logging epic and Google Analytics may not even load. We need to use some tool that can track visual regressions.

**Comment by wholesomedev** [comment]
Looks like [BrowserStack](https://www.browserstack.com/screenshots) might give us this capability?

**Comment by forabi** [comment]
Nice! I was thinking of some thing more automated though (like https://percy.io/). I'll take a look at a few solutions.

**Comment by wholesomedev** [comment]
@forabi I looked at Percy. Based on my understanding, Percy doesn't support multiple browsers. It doesn't even let us choose a browser. It will render our DOM in a "modern browser" and if it sees pixel differences, it will notify us?

I don't see how this can be easily automated without a very intelligent and fine-tuned artificial intelligence.

The way I imagine this would work for us is kind of similar to how we used to do perf-reports. We would manually check a daily report of screenshots on different browsers.

**Comment by forabi** [comment]
> It will render our DOM in a "modern browser" and if it sees pixel differences, it will notify us?

Percy was just one suggestion. We could probably find a similar service which allows choosing older browsers. If not, we could use BrowserStack with something like [pixelmatch](https://github.com/mapbox/pixelmatch) to diff screenshots on the same browser.

**Comment by forabi** [comment]
I've looked more into this and I think it would be complicated to do this on CI because it would need a staging environment. I think the screenshot and diff with `track-performance` appraoch would work fine for us.

**Comment by wholesomedev** [comment]
👍

**Comment by forabi** [comment]
I'm going to re-open this until we add a panel to Splunk dashboard to report the screenshots diffs.

**Comment by wholesomedev** [comment]
Yeah, I was wondering where we were going to post these images. Looks like Splunk allows [adding images](https://answers.splunk.com/answers/136162/add-picture-to-dashboard.html) to dashboards. Are we going to do something like that?

**Comment by forabi** [comment]
That worked! (although we should maybe consider cropping the image :smile:)

![screenshot from 2018-06-13 12-55-24](https://user-images.githubusercontent.com/1012761/41344232-4271193a-6f09-11e8-886c-04c662829472.png)

**Comment by forabi** [comment]
I improved this panel by adding overflow on the image and allowing the screenshot to be loaded dynamically instead of being hardcoded. This allows selecting the page URL:

![screenshot from 2018-06-13 23-09-13](https://user-images.githubusercontent.com/1012761/41375486-ee1205d8-6f5e-11e8-9b69-f2c43846b831.png)

I'd like to make this even more dynamic by avoiding hardcoded page URLs in the dropdown and possibly also allowing selection of browser/OS combination.

**Comment by forabi** [comment]
Done!

![screenshot from 2018-06-13 23-55-11](https://user-images.githubusercontent.com/1012761/41377600-3b898c36-6f65-11e8-8c63-c9413c28fe02.png)

**Comment by forabi** [comment]
I think this issue can now be closed. :tada:

**Comment by wholesomedev** [comment]
Ooh, that's neat. And the image is a clickable link to the full size!

Now we'll know if things get screwed up for Chrome 41!
