### ISSUE TITLE
Detect circular dependencies when bundling

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#52]
In my experience, circular dependencies cause hard to debug issues. I think we should show a warning when we inadvertently create a circular dependency

This webpack plugin can help https://github.com/aackerman/circular-dependency-plugin

**Comment by levsthings** [comment]
This seems to be a useful tool, I'll look into it's integration and I'll let you know the outcome.

**Comment by levsthings** [comment]
Unfortunately this package doesn't have type definitions, I'll see if I can get it sorted.
