### ISSUE TITLE
Move management of process-image resources to the respective CloudFormation stack

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#529]
As part of our efforts to move all infrastructure management to code, we should move the management of the following resources used by `process-image` to the respective `serverless.yml` file:

* S3 bucket for unprocessed images
* S3 bucket for processed images
* CloudFront distribution for the processed images
* Route 53 records for `photos.hollowverse.com`

**Comment by forabi** [comment]
Hmm, I'm wondering if `process-image` is the right place for the CloudFront distribution and target bucket. What if we, for any reason, decide to deprecate `process-image`? We sure want to keep the NP photos and `photos.hollowverse.com`.

**Comment by forabi** [comment]
We could set a deletion policy on these resources to prevent deleting them on stack deletion, but it still feels like `photos.hollowverse.com` and the processed image bucket should be independent from `process-image`. `hollowverse/infrastructure` might be a better place to manage these.

**Comment by wholesomedev** [comment]
>hollowverse/infrastructure might be a better place to manage these.

Yeah, I think that makes sense

**Comment by forabi** [comment]
Well, due to a limitation in CloudFormation ([relevant issue](https://github.com/serverless/serverless/issues/4284)), we won't be able to manage the source bucket with Terraform. It has to be managed by the same CloudFormation stack that sets up the S3 event that triggers processing of images.

I've moved the management of the source bucket to `process-image`, and the target bucket and `photos.hollowverse.com` to Terraform.
