### ISSUE TITLE
Shrinkwrap dependencies

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#53]
We need to shrinkwrap dependencies and make greenkeeper and the CI work with a shrinkwrapped project.

**Comment by levsthings** [comment]
https://github.com/hollowverse/hollowverse/issues/56 's outcome will resolve this issue. We'll either switch everything to `shrinkwrap` or `yarn`

**Comment by levsthings** [comment]
https://github.com/hollowverse/hollowverse/pull/57 implements Yarn.
