### ISSUE TITLE
Set up Splunk to use the new logging infrastructure

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#536]
* [x] Configure inputs to use new SQS queues
* [x] Also remove old resources:
  * [x] Old buckets for processed and unprocessed photos
  * [x] CF distribution for old photos bucket
  * [x] Unmanaged SQS queues
  * [x] Old logs bucket

**Comment by forabi** [comment]
Done!

**Comment by wholesomedev** [comment]
👍
