### ISSUE TITLE
Performance reports are missing Browserstack screenshots

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#552]
The latest report failed with status code `403` and previous screenshot jobs on Browserstack failed with `timed-out` state.

**Comment by forabi** [comment]
Oops! I've tracked this down to the following error:

```
Your plan has reached its limit of 100 screenshots. Please <a href='/accounts/subscriptions/screenshots'>upgrade your Screenshots plan</a> to get unlimited access.
```

@wholesomedev What do you think we should do?

**Comment by wholesomedev** [comment]
I'll go ahead and file an application for an open source account. I'll let you know how it goes.

**Comment by forabi** [comment]
I can confirm we are now able to fetch screenshots from BrowserStack API.
