### ISSUE TITLE
Update help copy in our READMEs

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#557]
At the bottoms of our README files, we have the following copy:

```
If you'd like to tell us something, or need help with anything...
```

I think it's too verbose. Can we update it to...

```
If you need help or wanna get in touch...
```

Affected repos:

- [x] hollowverse
- [x] api
- [x] route-request
- [x] config
- [x] track-performance
- [x] process-image
- [x] utils
- [x] architecture
- [x] infrastructure
- [x] clown
- [x] build-env
- [x] validate-filenames

**Comment by forabi** [comment]
Done!
