### ISSUE TITLE
Revert back to Day 1 Architecture

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#589]
@forabi since you're moving on to new challenges and adventures, I think the best thing to do is to put Hollowverse in a dormant state for now. 

I think we should restore Day 1 Architecture and take offline all AWS and other services that are not required for Day 1 Architecture.

One exception is that we should keep HTTPS.

**Comment by forabi** [comment]
I'm going to start by destroying the development version of the infrastructure using Terraform.

**Comment by forabi** [comment]
> I'm going to start by destroying the development version of the infrastructure using Terraform.

Done. I've also removed all the development CloudFormation stacks and related deployment buckets.

**Comment by forabi** [comment]
Okay, I've removed all the resources that were used by the new Hollowverse infrastructure, including all S3 buckets and production stacks (turns out we don't need the Node.js proxy for HTTPS, CloudFront can already handle the redirection to HTTPs). Now on to the documentation part.
