### ISSUE TITLE
Protect `develop` from pushes

### ISSUE THREAD

**Issue by deltaidea** [hollowverse-archive/hollowverse#6]
Please protect the `master` and `develop` branches from accidental pushes and to enforce code reviews.

Go to Settings > Branches > `develop`:

![image](https://cloud.githubusercontent.com/assets/4950036/24520904/8a55a682-15a3-11e7-98d3-aebefece535b.png)

This will ensure that we both don't miss anything and at least glance over changes before merging and deploying.

`master` is already protected but merges to it are going to be less frequent and with multiple PRs mashed together in `develop`. It's more comfortable to review everything when it's coming into `develop`.

**Comment by wholesomedev** [comment]
The problem with Git Flow is that code stays in `develop` until released and that doesn't go well with continuous delivery. 

After we release V1, I would like us to deploy all PRs as soon as possible. GitHub Flow works better for continuous delivery. Can you review [GitHub Flow](https://guides.github.com/introduction/flow/) as a substitute for Git Flow and let me know what you think?

**Comment by wholesomedev** [comment]
I like [this video](https://www.youtube.com/watch?v=cIJ4sKaoF8A) about the engineering culture and continuous delivery at GitHub. See if you can watch it. They also touch on the problem of synchronous vs asynchronous communication, which applies to us 

(P.S. I watched the video at 1.5x speed 😄)

**Comment by deltaidea** [comment]
👍  GitHub Flow makes a lot of sense - we already have PRs as a mechanism for peer review and catching bugs, what's the point of separating flow beyond that.
Let's completely switch to `master`.

If/when the need arises for more careful production deployment, we can keep auto-deploying to staging and transfer to prod manually with a button somewhere. In Git Flow merging to `master` is that button, but the GitHub version is cleaner.

**Comment by deltaidea** [comment]
I'll watch the video for sure, thanks!
