### ISSUE TITLE
Build 'Homepage'

### ISSUE THREAD

**Issue by levsthings** [hollowverse-archive/hollowverse#60]
The current iteration of the Homepage has some basic UI and functionality going but I'd like to work and improve some of the things there. Below are the things I need approval for:

Based on:
> Supported screen sizes
> 
> We are building Hollowverse with a mobile-only approach and we don't support any breakpoints for larger screens. Please use the iPhone 6 Preset in Chrome Developer Tools as a reference for development and discussions regarding the layout/design of the application.

Here are the things I want to do:
**app.tsx && app.scss**
- [x] Clean up all CSS selectors and implement a basic and clean flex box system for everything that is on these files (Header, Search Field etc.).
- [x] Get rid of the footer.
- [x] Possibly extract Header to a reusable child component. (If agreed, where in this folder structure?)

CC @msafih

**Comment by wholesomedev** [comment]
I think this is done. I'm gonna go ahead and close it.
