### ISSUE TITLE
Create a wiki for Workflows

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#87]
I need to create a wiki page where I document our various workflows and how we keep common configs.

I'm thinking we should move the entire [Project management](https://github.com/hollowverse/hollowverse/wiki#project-management) section from the Home wiki to this new Workflows wiki section as well...

**Comment by levsthings** [comment]
Good idea!

**Comment by forabi** [comment]
@msafih Can I help with this?

**Comment by forabi** [comment]
@msafih Can this be closed now that we have [Contribution Workflow](https://github.com/hollowverse/hollowverse/wiki/Contribution-Workflow)?

**Comment by wholesomedev** [comment]
Yeah, I think we can close this
